// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
const AGENT_MCP_VERBS: &[&str] = &[
    "board.expand",
    "board.refresh",
    "board.subscribe",
    "board.unsubscribe",
    "tasks.ack",
    "tasks.cancel",
    "tasks.check",
    "tasks.create",
    "tasks.expand",
    "tasks.ask",
    "tasks.wait",
    "tasks.answer",
    "tasks.outcomes",
    "rooms.list",
    "rooms.messages",
    "rooms.claim",
    "rooms.speak",
];
fn agent_argument_fields(name: &str) -> Option<&'static [&'static str]> {
    match name {
        "board.expand" => Some(&["key", "frame_epoch"]),
        "board.refresh" => Some(&["frame_epoch"]),
        "board.subscribe" => Some(&["scopes"]),
        "board.unsubscribe" => Some(&["scopes"]),
        "tasks.ack" => Some(&["task_ref"]),
        "tasks.cancel" => Some(&["task_ref"]),
        "tasks.check" => Some(&[]),
        "tasks.create" => Some(&["spec", "label"]),
        "tasks.expand" => Some(&["task_ref"]),
        "tasks.ask" => Some(&["spec"]),
        "tasks.wait" => Some(&["spec"]),
        "tasks.answer" => Some(&["spec"]),
        "tasks.outcomes" => Some(&["spec"]),
        "rooms.list" => Some(&[]),
        "rooms.messages" => Some(&["room_ref", "turn_ref"]),
        "rooms.claim" => Some(&["room_ref", "turn_ref"]),
        "rooms.speak" => Some(&["spec", "room_ref"]),
        _ => None,
    }
}
fn agent_required_fields(name: &str) -> Option<&'static [&'static str]> {
    match name {
        "board.expand" => Some(&["key"]),
        "board.refresh" => Some(&[]),
        "board.subscribe" => Some(&["scopes"]),
        "board.unsubscribe" => Some(&["scopes"]),
        "tasks.ack" => Some(&["task_ref"]),
        "tasks.cancel" => Some(&["task_ref"]),
        "tasks.check" => Some(&[]),
        "tasks.create" => Some(&["spec"]),
        "tasks.expand" => Some(&["task_ref"]),
        "tasks.ask" => Some(&["spec"]),
        "tasks.wait" => Some(&["spec"]),
        "tasks.answer" => Some(&["spec"]),
        "tasks.outcomes" => Some(&["spec"]),
        "rooms.list" => Some(&[]),
        "rooms.messages" => Some(&["room_ref"]),
        "rooms.claim" => Some(&["room_ref", "turn_ref"]),
        "rooms.speak" => Some(&["spec", "room_ref"]),
        _ => None,
    }
}
fn agent_continuable(name: &str) -> bool {
    matches!(
        name,
        "board.expand"
            | "tasks.check"
            | "tasks.expand"
            | "tasks.outcomes"
            | "rooms.list"
            | "rooms.messages"
    )
}
fn agent_filtered_read(name: &str) -> bool {
    matches!(
        name,
        "board.expand" | "board.refresh" | "board.subscribe" | "board.unsubscribe" | "tasks.check"
    )
}
fn agent_unscoped(name: &str) -> bool {
    matches!(
        name,
        "tasks.create"
            | "tasks.ask"
            | "tasks.wait"
            | "tasks.answer"
            | "tasks.outcomes"
            | "rooms.list"
            | "rooms.messages"
            | "rooms.claim"
            | "rooms.speak"
    )
}
fn agent_writes(name: &str) -> bool {
    matches!(
        name,
        "tasks.ack"
            | "tasks.cancel"
            | "tasks.create"
            | "tasks.ask"
            | "tasks.wait"
            | "tasks.answer"
            | "rooms.claim"
            | "rooms.speak"
    )
}
