// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
const AGENT_MCP_VERBS: &[&str] = &[
    "board.expand",
    "board.refresh",
    "board.subscribe",
    "board.unsubscribe",
    "tasks.ack",
    "tasks.cancel",
    "tasks.check",
    "tasks.create",
    "tasks.expand",
    "tasks.ask",
    "tasks.wait",
    "tasks.answer",
    "tasks.outcomes",
    "rooms.list",
    "rooms.messages",
    "rooms.claim",
    "rooms.speak",
];
pub(super) fn agent_binding(family: McpVerbFamily, verb: &str) -> Option<McpVerbBinding> {
    match (family, verb) {
        (McpVerbFamily::Tasks, "ask") => Some(McpVerbBinding::TasksAsk),
        (McpVerbFamily::Tasks, "wait") => Some(McpVerbBinding::TasksWait),
        (McpVerbFamily::Tasks, "answer") => Some(McpVerbBinding::TasksAnswer),
        (McpVerbFamily::Tasks, "outcomes") => Some(McpVerbBinding::TasksOutcomes),
        (McpVerbFamily::Rooms, "list") => Some(McpVerbBinding::RoomsList),
        (McpVerbFamily::Rooms, "messages") => Some(McpVerbBinding::RoomsMessages),
        (McpVerbFamily::Rooms, "claim") => Some(McpVerbBinding::RoomsClaim),
        (McpVerbFamily::Rooms, "speak") => Some(McpVerbBinding::RoomsSpeak),
        _ => None,
    }
}
pub(super) const fn agent_argument_fields(
    binding: McpVerbBinding,
) -> Option<&'static [&'static str]> {
    match binding {
        McpVerbBinding::TasksAsk => Some(&["spec"]),
        McpVerbBinding::TasksWait => Some(&["task_ref", "key"]),
        McpVerbBinding::TasksAnswer => Some(&["spec"]),
        McpVerbBinding::TasksOutcomes => Some(&["task_ref"]),
        McpVerbBinding::RoomsList => Some(&[]),
        McpVerbBinding::RoomsMessages => Some(&["room_ref", "turn_ref"]),
        McpVerbBinding::RoomsClaim => Some(&["room_ref", "turn_ref"]),
        McpVerbBinding::RoomsSpeak => Some(&["spec", "room_ref"]),
        _ => None,
    }
}
pub(super) const fn agent_required_fields(
    binding: McpVerbBinding,
) -> Option<&'static [&'static str]> {
    match binding {
        McpVerbBinding::TasksAsk => Some(&["spec"]),
        McpVerbBinding::TasksWait => Some(&["task_ref", "key"]),
        McpVerbBinding::TasksAnswer => Some(&["spec"]),
        McpVerbBinding::TasksOutcomes => Some(&["task_ref"]),
        McpVerbBinding::RoomsList => Some(&[]),
        McpVerbBinding::RoomsMessages => Some(&["room_ref"]),
        McpVerbBinding::RoomsClaim => Some(&["room_ref", "turn_ref"]),
        McpVerbBinding::RoomsSpeak => Some(&["spec", "room_ref"]),
        _ => None,
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum McpVerbBinding {
    BoardExpand,
    BoardRefresh,
    BoardSubscribe,
    BoardUnsubscribe,
    TasksAck,
    TasksCancel,
    TasksCheck,
    TasksCreate,
    TasksExpand,
    TasksAsk,
    TasksWait,
    TasksAnswer,
    TasksOutcomes,
    RoomsList,
    RoomsMessages,
    RoomsClaim,
    RoomsSpeak,
    Memory(VaultReadMethod),
}
