#!/usr/bin/env python3
'Generate agent SDK transports from agent-verbs.json; --check never writes.'
import argparse
import json
import subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = json.loads((Path(__file__).with_name('agent-verbs.json')).read_text())
ROWS = MANIFEST['verbs']
NAMES = MANIFEST['legacy_mcp'] + [row['name'] for row in ROWS if '.' in row['name']]
if len(set(MANIFEST['legacy_mcp'] + [row['name'] for row in ROWS])) != len(MANIFEST['legacy_mcp']) + len(ROWS): raise ValueError('duplicate SDK verb')
HEADER = '// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.\n'
def rust_type(value):
    return value.replace('crate::', 'oneiron::') if value.startswith('crate::') else 'oneiron::task_verb::sdk::' + value

NAPI_BOUNDARIES = {
    'witness': r'''
    /// Witnesses one conversational turn.
    #[napi]
    pub fn witness(&self, turn: NapiWitnessTurnInput) -> napi::Result<NapiWitnessReceipt> {
        let stamped = oneiron_remote::stamp_occurred_at(turn.occurred_at).map_err(facade_error)?;
        // Caller numbers are already validated; narrowing failure here is
        // an internal invariant failure, not bad input.
        let occurred_at = i64::try_from(stamped)
            .map_err(|_| boundary_error("occurred_at is out of range".to_owned()))?;
        let turn = NapiWitnessTurn {
            conversation_ref: turn.conversation_ref,
            turn_ref: turn.turn_ref,
            messages: turn.messages,
            occurred_at,
        };
        let engine_turn = witness_turn_to_engine(&turn).map_err(witness_input_error)?;
        let receipt = self.inner.witness(&engine_turn).map_err(facade_error)?;
        Ok(witness_receipt_from_engine(receipt))
    }
''',
    'claim_upsert': r'''
    /// Upserts one claim through the gated claim-candidate path.
    #[napi]
    pub fn claim_upsert(&self, claim: NapiClaimInput) -> napi::Result<NapiCommitReceipt> {
        let engine_claim = claim_input_to_engine(&claim).map_err(facade_error)?;
        let receipt = self
            .inner
            .claim_upsert(&engine_claim)
            .map_err(facade_error)?;
        Ok(commit_receipt_from_engine(receipt))
    }
''',
    'recall': r'''
    /// Effort-dialed retrieval into a memory pack.
    #[napi]
    pub fn recall(
        &self,
        query: String,
        effort: Option<String>,
        scope: Option<NapiRecallScope>,
        limit: Option<f64>,
        format: Option<String>,
    ) -> napi::Result<NapiMemoryPack> {
        let effort = oneiron_remote::parse_effort(effort.as_deref().unwrap_or("medium"))
            .map_err(facade_error)?;
        let scope = recall_scope_to_engine(scope);
        let limit = limit
            .map(limit_to_engine)
            .transpose()
            .map_err(facade_error)?
            .unwrap_or(oneiron_remote::DEFAULT_RECALL_LIMIT);
        let pack = self
            .inner
            .recall(&query, effort, &scope, limit, format.as_deref())
            .map_err(facade_error)?;
        memory_pack_from_engine(pack).map_err(boundary_error)
    }
''',
    'receipts': r'''
    /// Gate decision receipts, newest first.
    #[napi]
    pub fn receipts(&self, limit: Option<f64>) -> napi::Result<Vec<NapiGateReceipt>> {
        let limit = limit
            .map(limit_to_engine)
            .transpose()
            .map_err(facade_error)?
            .unwrap_or(oneiron_remote::DEFAULT_RECEIPTS_LIMIT);
        let records = self.inner.receipts(limit).map_err(facade_error)?;
        records
            .into_iter()
            .map(|record| gate_receipt_from_engine(record).map_err(boundary_error))
            .collect()
    }
''',
}
PY_BOUNDARIES = {
    'witness': r'''
    /// Witnesses one conversational turn.
    fn witness(&self, py: Python<'_>, turn_json: &str) -> PyResult<String> {
        let input: WitnessTurnInput = decode(turn_json, "the witness turn")?;
        let turn = input.into_engine().map_err(raise)?;
        let receipt = py.detach(|| self.inner.witness(&turn)).map_err(raise)?;
        encode(&receipt)
    }
''',
    'claim_upsert': r'''
    /// Upserts one claim through the gated claim-candidate path.
    fn claim_upsert(&self, py: Python<'_>, claim_json: &str) -> PyResult<String> {
        let claim: ClaimInput = decode(claim_json, "the claim")?;
        let receipt = py
            .detach(|| self.inner.claim_upsert(&claim))
            .map_err(raise)?;
        encode(&receipt)
    }
''',
    'recall': r'''
    /// Effort-dialed retrieval into a memory pack.
    #[pyo3(signature = (query, effort=None, scope_json=None, limit=None, format=None))]
    fn recall(
        &self,
        py: Python<'_>,
        query: String,
        effort: Option<&str>,
        scope_json: Option<&str>,
        limit: Option<usize>,
        format: Option<String>,
    ) -> PyResult<String> {
        let effort = oneiron_remote::parse_effort(effort.unwrap_or("medium")).map_err(raise)?;
        let scope = match scope_json {
            Some(json) => decode(json, "the recall scope")?,
            None => oneiron::memory::RecallScope::default(),
        };
        let limit = limit.unwrap_or(oneiron_remote::DEFAULT_RECALL_LIMIT);
        let pack = py
            .detach(|| {
                self.inner
                    .recall(&query, effort, &scope, limit, format.as_deref())
            })
            .map_err(raise)?;
        encode(&pack)
    }
''',
    'receipts': r'''
    /// Gate decision receipts, newest first.
    #[pyo3(signature = (limit=None))]
    fn receipts(&self, py: Python<'_>, limit: Option<usize>) -> PyResult<String> {
        let limit = limit.unwrap_or(oneiron_remote::DEFAULT_RECEIPTS_LIMIT);
        let receipts = py.detach(|| self.inner.receipts(limit)).map_err(raise)?;
        encode(&receipts)
    }
''',
}
TS_BOUNDARIES = {
    'witness': r'''
  /**
   * Witnesses one conversational turn.
   *
   * Omitting `occurredAt` stamps the current wall clock, in Unix seconds, at
   * the call boundary.
   */
  witness(turn: WitnessTurn): WitnessReceipt {
    return this.#call(() => this.#client.witness(turn))
  }
''',
    'claim_upsert': r'''
  /** Upserts one claim. The consent gate, not this call, decides approval. */
  claimUpsert(claim: ClaimInput): CommitReceipt {
    return this.#call(() => this.#client.claimUpsert(claim))
  }
''',
    'recall': r'''
  /**
   * Recalls a memory pack.
   *
   * `effort: "high"`, `"xhigh"`, or `"max"` is lease-gated and returns `LEASE_REQUIRED` until a
   * lease-bearing constructor exists; this package neither mints nor
   * simulates a lease.
   */
  recall(query: string, opts: RecallOptions = {}): MemoryPack {
    return this.#call(() =>
      this.#client.recall(query, opts.effort ?? "medium", opts.scope, opts.limit ?? 10, opts.format),
    )
  }
''',
    'receipts': r'''
  /** Governance receipts, newest first. */
  receipts(limit = 100): FacadeReceipt[] {
    return this.#call(() => this.#client.receipts(limit))
  }
''',
    'key_value_get': r'''
  /** Exact actor-owned worldless key lookup, never recall. */
  keyValueGet(request: KeyValueAddress): KeyValueItem | null {
    return this.#call(() => {
      const item = JSON.parse(this.#client.keyValueGet(keyedJson(request))) as WireItem | null
      return item === null ? null : itemFromWire(item)
    })
  }
''',
    'key_value_put': r'''
  /** Synchronous gated write. Review-required writes fail without changing the key. */
  keyValuePut(request: KeyValuePut): KeyValuePutReceipt {
    return this.#call(() => {
      const { requestId, ...rest } = request
      const result = JSON.parse(this.#client.keyValuePut(keyedJson({ ...rest, request_id: requestId }))) as
        { item: WireItem; replayed: boolean; receipt_ref: string }
      return { item: itemFromWire(result.item), replayed: result.replayed, receiptRef: result.receipt_ref }
    })
  }
''',
    'key_value_delete': r'''
  /** Retracts only the caller's current key; preserves claim history. */
  keyValueDelete(request: KeyValueAddress): KeyValueDeleteReceipt {
    return this.#call(() => {
      const result = JSON.parse(this.#client.keyValueDelete(keyedJson(request))) as
        { existed: boolean; receipt_refs: string[] }
      return { existed: result.existed, receiptRefs: result.receipt_refs }
    })
  }
''',
    'key_value_search': r'''
  /** Exact prefix search, ordered lexically and paginated after filtering. */
  keyValueSearch(request: KeyValueSearch): KeyValueItem[] {
    return this.#call(() => {
      const { namespacePrefix = [], ...rest } = request
      const result = JSON.parse(this.#client.keyValueSearch(keyedJson({ ...rest, namespace_prefix: namespacePrefix }))) as WireItem[]
      return result.map(itemFromWire)
    })
  }
''',
    'key_value_namespaces': r'''
  /** Exact segment namespace enumeration. Empty namespaces are not retained. */
  keyValueNamespaces(request: KeyValueNamespaces): string[][] {
    return this.#call(() => {
      const { maxDepth, ...rest } = request
      return JSON.parse(this.#client.keyValueNamespaces(keyedJson({ ...rest, max_depth: maxDepth }))) as string[][]
    })
  }
''',
}
PY_PUBLIC_BOUNDARIES = {
    'witness': r'''
    def witness(self, turn: dict[str, Any]) -> dict[str, Any]:
        """Witnesses one conversational turn.

        Omitting ``occurred_at`` stamps the current wall clock, in Unix
        seconds, at the call boundary.
        """
        return json.loads(_translate(lambda: self._client.witness(json.dumps(turn))))
''',
    'claim_upsert': r'''
    def claim_upsert(self, claim: dict[str, Any]) -> dict[str, Any]:
        """Upserts one claim. The consent gate, not this call, decides approval."""
        return json.loads(
            _translate(lambda: self._client.claim_upsert(json.dumps(claim)))
        )
''',
    'recall': r'''
    def recall(
        self,
        query: str,
        *,
        effort: str = "medium",
        scope: dict[str, Any] | None = None,
        limit: int = 10,
        format: str | None = None,
    ) -> dict[str, Any]:
        """Recalls a memory pack.

        ``effort="high"`` is lease-gated and raises ``LEASE_REQUIRED`` until a
        lease-bearing constructor exists; this package neither mints nor
        simulates a lease. ``format`` takes the engine's exact tokens:
        ``"json"``, ``"yaml"``, ``"toon"``, ``"md"``, ``"txt"``.
        """
        return json.loads(
            _translate(
                lambda: self._client.recall(
                    query,
                    effort,
                    json.dumps(scope) if scope is not None else None,
                    limit,
                    format,
                )
            )
        )
''',
    'receipts': r'''
    def receipts(self, limit: int = 100) -> list[dict[str, Any]]:
        """Governance receipts, newest first."""
        return json.loads(_translate(lambda: self._client.receipts(limit)))
''',
    'key_value_get': r'''
    def key_value_get(self, request: dict[str, Any]) -> dict[str, Any] | None:
        """Exact actor-owned worldless keyed memory; typed engine errors pass through."""
        return json.loads(_translate(lambda: self._client.key_value_get(json.dumps(request, allow_nan=False))))
''',
    'key_value_put': r'''
    def key_value_put(self, request: dict[str, Any]) -> dict[str, Any]:
        """Exact actor-owned worldless keyed memory; typed engine errors pass through."""
        return json.loads(_translate(lambda: self._client.key_value_put(json.dumps(request, allow_nan=False))))
''',
    'key_value_delete': r'''
    def key_value_delete(self, request: dict[str, Any]) -> dict[str, Any]:
        """Exact actor-owned worldless keyed memory; typed engine errors pass through."""
        return json.loads(_translate(lambda: self._client.key_value_delete(json.dumps(request, allow_nan=False))))
''',
    'key_value_search': r'''
    def key_value_search(self, request: dict[str, Any]) -> list[dict[str, Any]]:
        """Exact actor-owned worldless keyed memory; typed engine errors pass through."""
        return json.loads(_translate(lambda: self._client.key_value_search(json.dumps(request, allow_nan=False))))
''',
    'key_value_namespaces': r'''
    def key_value_namespaces(self, request: dict[str, Any]) -> list[list[str]]:
        """Exact actor-owned worldless keyed memory; typed engine errors pass through."""
        return json.loads(_translate(lambda: self._client.key_value_namespaces(json.dumps(request, allow_nan=False))))
''',
}
TS_NATIVE_BOUNDARIES = {'key_value_get': '  keyValueGet(requestJson: string): string\n', 'key_value_put': '  keyValuePut(requestJson: string): string\n', 'key_value_delete': '  keyValueDelete(requestJson: string): string\n', 'key_value_search': '  keyValueSearch(requestJson: string): string\n', 'key_value_namespaces': '  keyValueNamespaces(requestJson: string): string\n', 'witness': '  witness(turn: WitnessTurn): WitnessReceipt\n', 'claim_upsert': '  claimUpsert(claim: ClaimInput): CommitReceipt\n', 'recall': '  recall(\n    query: string,\n    effort: string | undefined,\n    scope: RecallScope | undefined,\n    limit: number | undefined,\n    format: string | undefined,\n  ): MemoryPack\n', 'receipts': '  receipts(limit: number | undefined): FacadeReceipt[]\n'}

REMOTE_DOCS = {
    'witness': "    /// Witnesses one conversational turn.\n    ///\n    /// `turn.occurred_at` is already stamped by the caller through\n    /// [`stamp_occurred_at`], because the engine DTO's field is required and a\n    /// backend cannot tell an omitted `0` from a deliberate one.\n",
    'claim_upsert': '    /// Upserts one claim through the gated claim-candidate path.\n',
    'recall': "    /// Recalls a memory pack.\n    ///\n    /// The lease argument the engine takes is `None` and is NOT a client\n    /// input: no lease issuer exists, and a bearer slip is not one. An\n    /// `Effort::High` call therefore returns the engine's `LEASE_REQUIRED`\n    /// through both backends, spelled identically.\n",
    'receipts': '    /// Lists governance receipts, newest first.\n',
    'key_value_get': '    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.\n',
    'key_value_put': '    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.\n',
    'key_value_delete': '    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.\n',
    'key_value_search': '    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.\n',
    'key_value_namespaces': '    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.\n',
}
SERVER_RECALL_DOC = "/// `POST /v1/core/facade/recall` → `Memory::recall`.\n///\n/// The lease argument is `None` and is not a client input: no lease-issuer\n/// exists, and a bearer slip is not one. `Effort::High` therefore returns the\n/// engine's own `LEASE_REQUIRED`, which this projection forwards as that exact\n/// code — the bindings neither mint nor simulate a lease.\n"

PY_STUB_BOUNDARIES = {
    'witness': '    def witness(self, turn: WitnessTurn) -> WitnessReceipt: ...\n',
    'claim_upsert': '    def claim_upsert(self, claim: ClaimInput) -> CommitReceipt: ...\n',
    'recall': '    def recall(\n        self,\n        query: str,\n        *,\n        effort: Effort = "medium",\n        scope: RecallScope | None = None,\n        limit: int = 10,\n        format: PackFormat | None = None,\n    ) -> MemoryPack: ...\n',
    'receipts': '    def receipts(self, limit: int = 100) -> list[FacadeReceipt]: ...\n',
    'key_value_get': '    def key_value_get(self, request: KeyValueAddress) -> KeyValueItem | None: ...\n',
    'key_value_put': '    def key_value_put(self, request: KeyValuePut) -> KeyValuePutReceipt: ...\n',
    'key_value_delete': '    def key_value_delete(self, request: KeyValueAddress) -> KeyValueDeleteReceipt: ...\n',
    'key_value_search': '    def key_value_search(self, request: KeyValueSearch) -> list[KeyValueItem]: ...\n',
    'key_value_namespaces': '    def key_value_namespaces(self, request: KeyValueNamespaces) -> list[list[str]]: ...\n',
}

def js_method(name):
    parts = name.replace('.', '_').split('_')
    return parts[0] + ''.join(part.title() for part in parts[1:])

def ts_facade(row):
    name = row['name']
    if name in TS_BOUNDARIES:
        return TS_BOUNDARIES[name]
    method = js_method(name)
    return f'  {method}(input: unknown): unknown {{ return this.#call(() => this.#client.{method}(input)) }}\n'

def python_facade(row):
    name = row['name']
    if name in PY_PUBLIC_BOUNDARIES:
        return PY_PUBLIC_BOUNDARIES[name]
    return f'    def {name}(self, input: object) -> Any:\n        return self._agent_verb("{name}", input)\n'

def mcp_dispatch():
    result = """fn execute_mcp_agent_verb(
        server: &SyncServer,
        args: &McpVerbToolArgs,
        actor: &McpResolvedActor,
    ) -> Result<(Value, crate::mcp::McpPageSource), McpGatewayError> {
        let a = &args.payload.arguments;
        let invalid = || McpGatewayError::new(-32602, "tool_args_invalid", "invalid typed agent-verb argument");
        let memory = server.vault.memory(actor.actor_ref, actor.actor_class);
        match args.tool.name {
"""
    for row in ROWS:
        if row['mcp'] == 'none':
            continue
        fields = row['mcp_fields']
        required = row.get('mcp_required_fields', fields)
        tree = {}
        root_value = None
        equalities = []
        for field, path in fields.items():
            if path.startswith('='):
                equalities.append(f'if a.{field}.as_deref() != Some(input.{path[1:]}.as_str()) {{ return Err(invalid()); }}')
                continue
            value = f'a.{field}.clone()'
            if field in required:
                value += '.ok_or_else(invalid)?'
            if path == '$':
                root_value = value
            else:
                target = tree
                parts = path.split('.')
                for part in parts[:-1]:
                    target = target.setdefault(part, {})
                target[parts[-1]] = value
        def object_expr(tree):
            return '{' + ','.join(json.dumps(k) + ':' + (object_expr(v) if isinstance(v, dict) else v) for k, v in tree.items()) + '}'
        value = root_value if root_value is not None else 'json!(' + object_expr(tree) + ')'
        result += f'{json.dumps(row["name"])} => {{\n'
        result += f'let input: {rust_type(row["input"])} = serde_json::from_value({value}).map_err(|_| invalid())?;\n'
        result += '\n'.join(equalities) + '\n'
        result += f'let output = oneiron::task_verb::sdk::{row["name"].replace(".", "_")}(&memory, input).map_err(mcp_facade_error)?;\n'
        if 'page' in row:
            page = row['page']
            result += f'let source = crate::mcp::McpPageSource::scoped_window(output.{page["rows"]}.len(), 0, 0, output.{page["cursor"]}.is_none());\n'
        else:
            count = 'output.len()' if row['output'].startswith('Vec<') else '1'
            result += f'let source = crate::mcp::McpPageSource::complete({count});\n'
        result += 'let value = serde_json::to_value(output).map_err(|_| McpGatewayError::new(-32603, "engine_error", "typed agent result cannot be encoded"))?; Ok((value, source)) },\n'
    result += '_ => Err(invalid()), } }\n'
    return result

def outputs():
    core = HEADER + 'pub const AGENT_VERBS: &[&str] = &[' + ','.join(json.dumps(r['name']) for r in ROWS) + '];\n'
    core += "pub fn input_schema(verb: &str) -> Option<serde_json::Value> { Some(match verb {\n"
    for r in ROWS:
        core += f'{json.dumps(r["name"])} => crate::code_run::vault_read::request_schema::<{r["input"]}>(),\n'
    core += '_ => return None, }) }\n'
    core += "pub fn mcp_arguments_schema(verb: &str) -> Option<serde_json::Value> { let schema = input_schema(verb)?; let mut properties = serde_json::Map::new(); let required: &[&str] = match verb {\n"
    for r in ROWS:
        if r['mcp'] == 'none': continue
        core += f'{json.dumps(r["name"])} => {{\n'
        for field, path in r['mcp_fields'].items():
            pointer = '' if path == '$' else ''.join('/properties/' + part for part in path.removeprefix('=').split('.'))
            core += f'properties.insert({json.dumps(field)}.to_owned(), schema.pointer({json.dumps(pointer)})?.clone());\n'
        core += '&' + json.dumps(list(r.get('mcp_required_fields', r['mcp_fields']))) + '},\n'
    core += '_ => return None, }; Some(serde_json::json!({"type": "object", "additionalProperties": false, "required": required, "properties": properties})) }\n'
    core += "pub fn validate_input(verb: &str, value: &serde_json::Value) -> MemoryResult<()> { match verb {\n"
    for r in ROWS:
        checks = r.get('admission', {}).get('validate', '')
        binding = 'input' if checks else '_input'
        core += f'{json.dumps(r["name"])} => {{ let {binding}: {r["input"]} = decode(value.clone())?; {checks} }},\n'
    core += '_ => return Err(MemoryError::bad_request("unknown SDK agent verb")), } Ok(()) }\n'
    core += "pub fn invoke(memory: &Memory<'_>, verb: &str, value: serde_json::Value) -> MemoryResult<serde_json::Value> { match verb {\n"
    for r in ROWS:
        method = r['name'].replace('.', '_')
        core += f'{json.dumps(r["name"])} => encode({method}(memory, decode(value)?)?),\n'
    core += '_ => Err(MemoryError::bad_request("unknown SDK agent verb")),\n}}\n'
    for r in ROWS:
        method = r['name'].replace('.', '_')
        binding = '_input' if r['input'] == 'EmptyRequest' else 'input'
        checks = r.get('admission', {}).get('validate', '')
        core += f"pub fn {method}(memory: &Memory<'_>, {binding}: {r['input']}) -> MemoryResult<{r['output']}> {{ {checks} Ok({r['call']}) }}\n"
    server = HEADER + 'use super::*;\npub(super) fn routes() -> Router<Arc<SyncServer>> { Router::new()\n'
    for r in ROWS:
        method=r['name'].replace('.','_')
        server += f'.route("/{r["name"]}", post({method}))\n'
    server += '}\n'
    for r in ROWS:
        method=r['name'].replace('.','_')
        if r['name'] == 'recall': server += SERVER_RECALL_DOC
        server += f'''async fn {method}(auth: CoreAuth, State(server): State<Arc<SyncServer>>, payload: Result<Json<serde_json::Value>, JsonRejection>) -> Result<Json<serde_json::Value>, FacadeApiError> {{
        auth.require(CoreScope::{r["scope"]})?;
        {'auth.require_unrestricted_record_scope()?;' if r.get('admission', {}).get('unrestricted_record_scope') else ''}
        let value = facade_json(payload)?;
        {f'oneiron::task_verb::sdk::validate_input("{r["name"]}", &value)?;' if 'admission' in r else ''}
        let (actor, class) = facade_actor(&auth)?;
        Ok(Json(oneiron::task_verb::sdk::invoke(&server.vault.memory(actor,class), "{r["name"]}", value)?))
        }}\n'''
    remote = HEADER + 'use super::*;\n'
    facade=[r['name'] for r in ROWS]
    remote += f'pub const FACADE_VERB_CATALOG: [&str; {len(facade)}] = '+json.dumps(facade)+';\nimpl OneironClient {\n'
    remote += '''pub fn agent_verb(&self, verb: &str, input: serde_json::Value) -> Result<serde_json::Value, MemoryError> {
        self.ensure_dispatch_pid()?;
        if !oneiron::task_verb::sdk::AGENT_VERBS.contains(&verb) { return Err(crate::error::bad_request("unknown SDK agent verb", &["Use a verb from the SDK catalog."])); }
        oneiron::task_verb::sdk::validate_input(verb, &input)?;
        match &self.backend {
            Backend::Embedded(client) => oneiron::task_verb::sdk::invoke(&client.memory(), verb, input),
            Backend::Remote(client) => client.call(verb, &input),
        }
    }
'''
    for r in ROWS:
        method=r['name'].replace('.','_')
        out=r['output'].replace('crate::', 'oneiron::')
        if r['name'] == 'recall':
            value_input = '&input'
            declaration = 'query: &str, effort: oneiron::memory::Effort, scope: &oneiron::memory::RecallScope, limit: usize, format: Option<&str>'
            input_value = 'let input = oneiron::task_verb::sdk::RecallRequest { query: query.to_owned(), effort: Some(effort), scope: Some(scope.clone()), limit: Some(limit), format: format.map(str::to_owned) };'
        elif r['name'] == 'receipts':
            value_input = '&input'
            declaration = 'limit: usize'
            input_value = 'let input = oneiron::task_verb::sdk::ReceiptsRequest { limit: Some(limit) };'
        else:
            value_input = 'input'
            declaration = f'input: &{rust_type(r["input"])}'
            input_value = ''
        remote += REMOTE_DOCS.get(r['name'], '')
        remote += f'''pub fn {method}(&self, {declaration}) -> Result<{out}, MemoryError> {{
            {input_value}
            let value = serde_json::to_value({value_input}).map_err(|_| crate::error::bad_request("SDK input encoding failed", &["Send the documented typed SDK input."]))?;
            let result = self.agent_verb("{r["name"]}", value)?;
            serde_json::from_value(result).map_err(|_| crate::error::bad_request("SDK output decoding failed", &["Report this SDK response mismatch."]))
        }}\n'''
    remote += '}\n'
    napi = HEADER + 'use super::*;\n#[napi]\nimpl NativeClient {\n'
    py = ''
    for r in ROWS:
        method=r['name'].replace('.','_')
        if r['name'] in NAPI_BOUNDARIES:
            napi += NAPI_BOUNDARIES[r['name']]
        elif r['name'].startswith('key_value_'):
            napi += f'''#[napi]
            pub fn {method}(&self, request_json: String) -> napi::Result<String> {{
                let input: serde_json::Value = serde_json::from_str(&request_json).map_err(|error| facade_error(oneiron::memory::MemoryError {{ code: oneiron::memory::MEMORY_CODE_BAD_REQUEST.to_owned(), message: format!("invalid keyed request: {{error}}"), suggestions: vec!["Use the documented keyed DTO.".to_owned()], successor_short_id: None, gate_denial: None }}))?;
                let output = self.inner.agent_verb("{r['name']}", input).map_err(facade_error)?;
                serde_json::to_string(&output).map_err(|error| boundary_error(error.to_string()))
            }}\n'''
        else:
            napi += f'''#[napi]
            pub fn {method}(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {{
                self.inner.agent_verb("{r['name']}", input).map_err(facade_error)
            }}\n'''
        if r['name'] in PY_BOUNDARIES:
            py += PY_BOUNDARIES[r['name']]
        else:
            py += f'''    fn {method}(&self, py: Python<'_>, input_json: &str) -> PyResult<String> {{
                let input: serde_json::Value = decode(input_json, "{r['name']}")?;
                let output = py.detach(|| self.inner.agent_verb("{r['name']}", input)).map_err(raise)?;
                encode(&output)
            }}\n'''
    napi += '}\n'
    ts = HEADER + 'export type AgentInvoke = (method: string, input: unknown) => unknown;\n'
    ts += '''export interface OutcomeBinding { source: {kind: "claim" | "event"; predicate: string} | {kind: "edge"; relation: string} | {kind: "stage"; campaign: string}; horizon: number; mapping: Record<string, boolean>; noise_weight: number; linked_by?: string | null }
export interface CalibrationPair { prediction: unknown; probability: number; outcome: {answer: string; fact: string; fact_value_hash: number[]; label: boolean; noise_weight: number; occurred_at: number} }
export interface TaskAskSpec { question: Record<string, unknown>; holders: string[]; idempotency_key: string; outcome_binding?: OutcomeBinding | null }
export interface TaskAskHandle { task_ref: string }
export interface TaskAskReceipt { handle: TaskAskHandle; count: number; replayed: boolean }
export interface TaskAskAnswer { task_ref: string; actor_ref: string; result_ref: string; at: number; answer_ref: string | null; question_version: number | null }
export type TaskWaitOutcome = { Pending: {trap_ref: string} } | { Ready: TaskAskAnswer } | { AlreadyResumed: TaskAskAnswer };
export function agentVerbs(invoke: AgentInvoke) {
  return {
'''
    for family in ['tasks', 'rooms']:
        ts += family + ': {\n'
        for r in ROWS:
            fam, _, verb = r['name'].partition('.')
            if fam != family: continue
            method=fam+verb.title()
            if verb=='ask': decl='spec: TaskAskSpec'; value='spec'; result='TaskAskReceipt'
            elif verb=='wait': decl='handle: TaskAskHandle, stepKey = "sdk.wait"';value='{handle, step_key: stepKey}';result='TaskWaitOutcome'
            elif verb=='answer':decl='handle: TaskAskHandle, resultRef: string';value='{handle, result_ref: resultRef}';result='TaskAskAnswer'
            elif verb=='outcomes':decl='handle: TaskAskHandle';value='handle';result='CalibrationPair[]'
            elif verb=='list':decl='';value='{}';result='unknown[]'
            elif verb=='messages':decl='roomRef: string, after?: string, limit?: number';value='{room_ref: roomRef, after, limit}';result='{rows: unknown[]; next_after: string | null}'
            elif verb=='claim':decl='roomRef: string, turnRef: string';value='{room_ref: roomRef, turn_ref: turnRef}';result='unknown'
            else: decl='turn: Record<string, unknown>';value='turn';result='unknown'
            ts += f'{verb}({decl}): {result} {{ return invoke("{method}", {value}) as {result} }},\n'
        ts += '},\n'
    ts += '}\n}\n'
    ts_native = '\n'.join(TS_NATIVE_BOUNDARIES[r['name']] if r['name'] in TS_NATIVE_BOUNDARIES else js_method(r['name'])+'(input: unknown): unknown' for r in ROWS)
    python = '# Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.\n'
    for family in ['tasks', 'rooms']:
        python += f'class {family.title()}Verbs:\n    def __init__(self, call):\n        self._call = call\n'
        for r in ROWS:
            fam, _, verb=r['name'].partition('.')
            if fam!=family:continue
            if verb=='wait':params='handle, step_key="sdk.wait"';value='{"handle": handle, "step_key": step_key}'
            elif verb=='answer':params='handle, result_ref';value='{"handle": handle, "result_ref": result_ref}'
            elif verb=='outcomes':params='handle';value='handle'
            elif verb=='list':params='';value='{}'
            elif verb=='messages':params='room_ref, after=None, limit=None';value='{"room_ref": room_ref, "after": after, "limit": limit}'
            elif verb=='claim':params='room_ref, turn_ref';value='{"room_ref": room_ref, "turn_ref": turn_ref}'
            else:params='spec';value='spec'
            comma=', ' if params else ''
            python+=f'    def {verb}(self{comma}{params}):\n        return self._call("{fam}_{verb}", {value})\n'
    legacy_tasks = [name for name in MANIFEST['legacy_mcp'] if name.startswith('tasks.')]
    tasks = sorted(set(legacy_tasks + [r['name'] for r in ROWS if r['name'].startswith('tasks.')]))
    rooms = [r['name'] for r in ROWS if r['name'].startswith('rooms.')]
    task_catalog = HEADER + f'pub const TASKS_VERBS: [&str; {len(tasks)}] = '+json.dumps(tasks)+';\n'
    task_catalog += '#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum TasksVerb { '+','.join(n.split('.')[1].title() for n in tasks)+' }\n'
    task_catalog += f'impl TasksVerb {{ pub const ALL: [Self; {len(tasks)}] = ['+','.join('Self::'+n.split('.')[1].title() for n in tasks)+'];\n'
    task_catalog += '#[must_use] pub const fn as_str(self) -> &' + "'static str { match self {\n"
    task_catalog += ''.join('Self::'+n.split('.')[1].title()+' => '+json.dumps(n)+',\n' for n in tasks)+'}}}\n'
    room_catalog=HEADER+f'pub const ROOMS_VERBS: [&str; {len(rooms)}] = '+json.dumps(rooms)+';\n'
    mcp_names = MANIFEST['legacy_mcp'] + [r['name'] for r in ROWS if r['mcp'] == 'tool-first']
    mcp=HEADER+'const AGENT_MCP_VERBS: &[&str] = &'+json.dumps(mcp_names)+';\n'
    mcp+='pub(super) fn agent_binding(family: McpVerbFamily, verb: &str) -> Option<McpVerbBinding> { match (family, verb) {\n'
    for r in ROWS:
        if r['mcp'] == 'none': continue
        family,verb=r['name'].split('.')
        mcp+=f'(McpVerbFamily::{family.title()}, "{verb}") => Some(McpVerbBinding::{family.title()}{verb.title()}),\n'
    mcp+='_ => None, }}\n'
    for function, field in [('agent_argument_fields', 'mcp_fields'), ('agent_required_fields', 'mcp_required_fields')]:
        mcp += f"pub(super) const fn {function}(binding: McpVerbBinding) -> Option<&'static [&'static str]> {{ match binding {{\n"
        for r in ROWS:
            if r['mcp'] == 'none': continue
            family, verb = r['name'].split('.')
            mcp += f'McpVerbBinding::{family.title()}{verb.title()} => Some(&'+json.dumps(list(r.get(field, r['mcp_fields'])))+'),\n'
        mcp += '_ => None, }}\n'
    mcp += '#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum McpVerbBinding {\n'
    mcp += ''.join(''.join(part.title() for part in name.split('.'))+',\n' for name in NAMES)
    mcp += 'Memory(VaultReadMethod),\n}\n'
    python_stub = '# Generated by scripts/sdk/generate.py.\nfrom typing import Any\n'
    for family in ['tasks', 'rooms']:
        python_stub += f'class {family.title()}Verbs:\n'
        for row in ROWS:
            fam, _, verb=row['name'].partition('.')
            if fam!=family:continue
            if verb=='wait': args='handle: dict[str, Any], step_key: str = "sdk.wait"'
            elif verb=='answer':args='handle: dict[str, Any], result_ref: str'
            elif verb=='messages':args='room_ref: str, after: str | None = None, limit: int | None = None'
            elif verb=='claim':args='room_ref: str, turn_ref: str'
            elif verb=='outcomes':args='handle: dict[str, Any]'
            elif verb=='list':args=''
            else:args='spec: dict[str, Any]'
            python_stub += f'    def {verb}(self'+(', '+args if args else '')+') -> Any: ...\n'
    files = {
        'crates/oneiron/src/task_verb/sdk_generated.rs':core,
        'crates/oneiron/src/task_verb/verb_catalog.rs':task_catalog,
        'crates/oneiron/src/workspace_roster/rooms/verb_catalog.rs':room_catalog,
        'crates/oneiron-server/src/mcp/agent_catalog.rs':mcp,
        'crates/oneiron-server/src/api/facade/agent_verbs.rs':server,
        'crates/oneiron-remote/src/agent_verbs.rs':remote,
        'crates/oneiron-napi/src/facade/client/agent_verbs.rs':napi,
        'packages/oneiron/src/agent-verbs.ts':ts,
        'crates/oneiron-py/python/oneiron/agent_verbs.py':python,
        'crates/oneiron-py/python/oneiron/agent_verbs.pyi':python_stub,
    }
    for path, start, end, body in [
        ('crates/oneiron-server/src/api/mcp_gateway/tasks_response.rs', '// BEGIN GENERATED MCP DISPATCH', '// END GENERATED MCP DISPATCH', mcp_dispatch()),
        ('crates/oneiron-py/python/oneiron/__init__.pyi', '# BEGIN GENERATED FACADE VERBS', '# END GENERATED FACADE VERBS', ''.join(PY_STUB_BOUNDARIES.get(r['name'], f"    def {r['name']}(self, input: object) -> Any: ...\n") for r in ROWS if '.' not in r['name'])),
        ('packages/oneiron/src/index.ts', '// BEGIN GENERATED FACADE VERBS', '// END GENERATED FACADE VERBS', ''.join(ts_facade(r) for r in ROWS if '.' not in r['name'])),
        ('crates/oneiron-py/python/oneiron/__init__.py', '# BEGIN GENERATED FACADE VERBS', '# END GENERATED FACADE VERBS', ''.join(python_facade(r) for r in ROWS if '.' not in r['name'])),
        ('crates/oneiron-py/src/lib.rs', '// BEGIN GENERATED AGENT VERBS', '// END GENERATED AGENT VERBS', py),
        ('packages/oneiron/src/native.ts', '// BEGIN GENERATED AGENT VERBS', '// END GENERATED AGENT VERBS', ts_native),
    ]:
        text=(ROOT/path).read_text()
        a=text.index(start)+len(start); b=text.index(end,a)
        files[path]=text[:a]+'\n'+body+'\n'+text[b:]
    for path, text in list(files.items()):
        if path.endswith('.rs'):
            result = subprocess.run(['rustfmt', '--edition', '2024', '--emit', 'stdout'], input=text, text=True, capture_output=True, cwd=ROOT, check=True)
            files[path] = result.stdout
    return files

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    stale=[]
    for path,text in outputs().items():
        p=ROOT/path
        if p.exists() and p.read_text()==text:continue
        stale.append(path)
        if not args.check:
            p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
    if args.check and stale:
        raise SystemExit('SDK-GENERATED-STALE: '+', '.join(stale))
if __name__=='__main__': main()
