#!/usr/bin/env python3
"""Project the engine's single typed verb declaration into the thin JS client.

Rust and napi include table.rs directly. This dependency-free generator emits
only the non-Rust projection. --check compares generation, not behavior.
"""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[2]
TABLE = ROOT / "crates/oneiron/src/memory/verb_table/table.rs"
OUTPUT = ROOT / "packages/oneiron-client/src/catalog.ts"


def generate():
    rows = re.findall(
        r'(\w+) => \{\s*method: (\w+), wire: "([^\"]+)", sdk: "([^\"]+)", scope: (\w+),'
        r'\s*request: ([^\n]+?), response: ([^\n]+?),\s*doc: "([^\"]+)",\s*\}',
        TABLE.read_text(),
    )
    if not rows:
        raise ValueError("empty SDK table")
    values = [dict(wire=w, sdk=s, scope=sc.lower(), request=req, response=resp, doc=d)
              for _, method, w, s, sc, req, resp, d in rows]
    if len({r["wire"] for r in values}) != len(values):
        raise ValueError("duplicate SDK wire name")
    return ("// Generated by scripts/sdk/generate.py from the engine typed verb table.\n"
            + "export const FACADE_CATALOG = " + json.dumps(values, indent=2) + " as const;\n"
            + "export type FacadeWireName = (typeof FACADE_CATALOG)[number][\"wire\"];\n"
            + "export type FacadeSdkName = (typeof FACADE_CATALOG)[number][\"sdk\"];\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            raise SystemExit("SDK projection stale: python3 scripts/sdk/generate.py")
    else:
        OUTPUT.write_text(result)


if __name__ == "__main__":
    main()
