#!/usr/bin/env python3
'Generate agent SDK transports from agent-verbs.json; --check never writes.'
import argparse
import json
import subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = json.loads((Path(__file__).with_name('agent-verbs.json')).read_text())
ROWS = MANIFEST['verbs']
NAMES = MANIFEST['legacy_mcp'] + [row['name'] for row in ROWS]
if len(set(NAMES)) != len(NAMES): raise ValueError('duplicate SDK verb')
HEADER = '// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.\n'
def rust_type(value):
    return value.replace('crate::', 'oneiron::') if value.startswith('crate::') else 'oneiron::task_verb::sdk::' + value

def outputs():
    core = HEADER + 'pub const AGENT_VERBS: &[&str] = &[' + ','.join(json.dumps(r['name']) for r in ROWS) + '];\n'
    core += "pub fn invoke(memory: &Memory<'_>, verb: &str, value: serde_json::Value) -> MemoryResult<serde_json::Value> { match verb {\n"
    for r in ROWS:
        binding = '_input' if r['input'] == 'EmptyRequest' else 'input'
        core += f'{json.dumps(r["name"])} => {{ let {binding}: {r["input"]} = decode(value)?; encode({r["call"]}) }},\n'
    core += '_ => Err(MemoryError::bad_request("unknown SDK agent verb")),\n}}\n'
    server = HEADER + 'use super::*;\npub(super) fn routes() -> Router<Arc<SyncServer>> { Router::new()\n'
    for r in ROWS:
        method=r['name'].replace('.','_')
        server += f'.route("/{r["name"]}", post({method}))\n'
    server += '}\n'
    for r in ROWS:
        method=r['name'].replace('.','_')
        server += f'''async fn {method}(auth: CoreAuth, State(server): State<Arc<SyncServer>>, payload: Result<Json<serde_json::Value>, JsonRejection>) -> Result<Json<serde_json::Value>, FacadeApiError> {{
        auth.require(CoreScope::{r["scope"]})?;
        let value = facade_json(payload)?;
        let (actor, class) = facade_actor(&auth)?;
        Ok(Json(oneiron::task_verb::sdk::invoke(&server.vault.memory(actor,class), "{r["name"]}", value)?))
        }}\n'''
    remote = HEADER + 'use super::*;\n'
    facade=MANIFEST['legacy_facade']+[r['name'] for r in ROWS]
    remote += f'pub const FACADE_VERB_CATALOG: [&str; {len(facade)}] = '+json.dumps(facade)+';\nimpl OneironClient {\n'
    remote += '''pub fn agent_verb(&self, verb: &str, input: serde_json::Value) -> Result<serde_json::Value, MemoryError> {
        self.ensure_dispatch_pid()?;
        if !oneiron::task_verb::sdk::AGENT_VERBS.contains(&verb) { return Err(crate::error::bad_request("unknown SDK agent verb", &["Use a tasks.* or rooms.* SDK agent verb."])); }
        match &self.backend {
            Backend::Embedded(client) => oneiron::task_verb::sdk::invoke(&client.memory(), verb, input),
            Backend::Remote(client) => client.call(verb, &input),
        }
    }
'''
    for r in ROWS:
        method=r['name'].replace('.','_')
        out=r['output'].replace('crate::', 'oneiron::')
        remote += f'''pub fn {method}(&self, input: &{rust_type(r["input"])}) -> Result<{out}, MemoryError> {{
            let value = serde_json::to_value(input).map_err(|_| crate::error::bad_request("SDK input encoding failed", &["Send the documented typed SDK input."]))?;
            let result = self.agent_verb("{r["name"]}", value)?;
            serde_json::from_value(result).map_err(|_| crate::error::bad_request("SDK output decoding failed", &["Report this SDK response mismatch."]))
        }}\n'''
    remote += '}\n'
    napi = HEADER + 'use super::*;\n#[napi]\nimpl NativeClient {\n'
    py = ''
    for r in ROWS:
        method=r['name'].replace('.','_')
        napi += f'''#[napi]
        pub fn {method}(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {{
            self.inner.agent_verb("{r["name"]}", input).map_err(facade_error)
        }}\n'''
        py += f'''    fn {method}(&self, py: Python<'_>, input_json: &str) -> PyResult<String> {{
        let input: serde_json::Value = decode(input_json, "{r["name"]}")?;
        let output = py.detach(|| self.inner.agent_verb("{r["name"]}", input)).map_err(raise)?;
        encode(&output)
    }}\n'''
    napi += '}\n'
    ts = HEADER + 'export type AgentInvoke = (method: string, input: unknown) => unknown;\n'
    ts += '''export interface OutcomeBinding { source: {kind: "claim" | "event"; predicate: string} | {kind: "edge"; relation: string} | {kind: "stage"; campaign: string}; horizon: number; mapping: Record<string, boolean>; noise_weight: number; linked_by?: string | null }
export interface CalibrationPair { prediction: unknown; probability: number; outcome: {answer: string; fact: string; fact_value_hash: number[]; label: boolean; noise_weight: number; occurred_at: number} }
export interface TaskAskSpec { question: Record<string, unknown>; holders: string[]; idempotency_key: string; outcome_binding?: OutcomeBinding | null }
export interface TaskAskHandle { task_ref: string }
export interface TaskAskReceipt { handle: TaskAskHandle; count: number; replayed: boolean }
export interface TaskAskAnswer { task_ref: string; actor_ref: string; result_ref: string; at: number; answer_ref: string | null; question_version: number | null }
export type TaskWaitOutcome = { Pending: {trap_ref: string} } | { Ready: TaskAskAnswer } | { AlreadyResumed: TaskAskAnswer };
export function agentVerbs(invoke: AgentInvoke) {
  return {
'''
    for family in ['tasks', 'rooms']:
        ts += family + ': {\n'
        for r in ROWS:
            fam,verb = r['name'].split('.')
            if fam != family: continue
            method=fam+verb.title()
            if verb=='ask': decl='spec: TaskAskSpec'; value='spec'; result='TaskAskReceipt'
            elif verb=='wait': decl='handle: TaskAskHandle, stepKey = "sdk.wait"';value='{handle, step_key: stepKey}';result='TaskWaitOutcome'
            elif verb=='answer':decl='handle: TaskAskHandle, resultRef: string';value='{handle, result_ref: resultRef}';result='TaskAskAnswer'
            elif verb=='outcomes':decl='handle: TaskAskHandle';value='handle';result='CalibrationPair[]'
            elif verb=='list':decl='';value='{}';result='unknown[]'
            elif verb=='messages':decl='roomRef: string, after?: string, limit?: number';value='{room_ref: roomRef, after, limit}';result='unknown[]'
            elif verb=='claim':decl='roomRef: string, turnRef: string';value='{room_ref: roomRef, turn_ref: turnRef}';result='unknown'
            else: decl='turn: Record<string, unknown>';value='turn';result='unknown'
            ts += f'{verb}({decl}): {result} {{ return invoke("{method}", {value}) as {result} }},\n'
        ts += '},\n'
    ts += '}\n}\n'
    ts_native = '\n'.join(r['name'].split('.')[0]+r['name'].split('.')[1].title()+'(input: unknown): unknown' for r in ROWS)
    python = '# Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.\n'
    for family in ['tasks', 'rooms']:
        python += f'class {family.title()}Verbs:\n    def __init__(self, call):\n        self._call = call\n'
        for r in ROWS:
            fam,verb=r['name'].split('.')
            if fam!=family:continue
            if verb=='wait':params='handle, step_key="sdk.wait"';value='{"handle": handle, "step_key": step_key}'
            elif verb=='answer':params='handle, result_ref';value='{"handle": handle, "result_ref": result_ref}'
            elif verb=='outcomes':params='handle';value='handle'
            elif verb=='list':params='';value='{}'
            elif verb=='messages':params='room_ref, after=None, limit=None';value='{"room_ref": room_ref, "after": after, "limit": limit}'
            elif verb=='claim':params='room_ref, turn_ref';value='{"room_ref": room_ref, "turn_ref": turn_ref}'
            else:params='spec';value='spec'
            comma=', ' if params else ''
            python+=f'    def {verb}(self{comma}{params}):\n        return self._call("{fam}_{verb}", {value})\n'
    legacy_tasks = [name for name in MANIFEST['legacy_mcp'] if name.startswith('tasks.')]
    tasks = sorted(set(legacy_tasks + [r['name'] for r in ROWS if r['name'].startswith('tasks.')]))
    rooms = [r['name'] for r in ROWS if r['name'].startswith('rooms.')]
    task_catalog = HEADER + f'pub const TASKS_VERBS: [&str; {len(tasks)}] = '+json.dumps(tasks)+';\n'
    task_catalog += '#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum TasksVerb { '+','.join(n.split('.')[1].title() for n in tasks)+' }\n'
    task_catalog += f'impl TasksVerb {{ pub const ALL: [Self; {len(tasks)}] = ['+','.join('Self::'+n.split('.')[1].title() for n in tasks)+'];\n'
    task_catalog += '#[must_use] pub const fn as_str(self) -> &' + "'static str { match self {\n"
    task_catalog += ''.join('Self::'+n.split('.')[1].title()+' => '+json.dumps(n)+',\n' for n in tasks)+'}}}\n'
    room_catalog=HEADER+f'pub const ROOMS_VERBS: [&str; {len(rooms)}] = '+json.dumps(rooms)+';\n'
    mcp=HEADER+'pub(super) fn agent_binding(family: McpVerbFamily, verb: &str) -> Option<McpVerbBinding> { match (family, verb) {\n'
    for r in ROWS:
        family,verb=r['name'].split('.')
        mcp+=f'(McpVerbFamily::{family.title()}, "{verb}") => Some(McpVerbBinding::{family.title()}{verb.title()}),\n'
    mcp+='_ => None, }}\n'
    for function, field in [('agent_argument_fields', 'mcp_fields'), ('agent_required_fields', 'mcp_required_fields')]:
        mcp += f"pub(super) const fn {function}(binding: McpVerbBinding) -> Option<&'static [&'static str]> {{ match binding {{\n"
        for r in ROWS:
            family, verb = r['name'].split('.')
            mcp += f'McpVerbBinding::{family.title()}{verb.title()} => Some(&'+json.dumps(r.get(field, r['mcp_fields']))+'),\n'
        mcp += '_ => None, }}\n'
    mcp += '#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum McpVerbBinding {\n'
    mcp += ''.join(''.join(part.title() for part in name.split('.'))+',\n' for name in NAMES)
    mcp += 'Memory(VaultReadMethod),\n}\n'
    python_stub = '# Generated by scripts/sdk/generate.py.\nfrom typing import Any\n'
    for family in ['tasks', 'rooms']:
        python_stub += f'class {family.title()}Verbs:\n'
        for row in ROWS:
            fam,verb=row['name'].split('.')
            if fam!=family:continue
            if verb=='wait': args='handle: dict[str, Any], step_key: str = "sdk.wait"'
            elif verb=='answer':args='handle: dict[str, Any], result_ref: str'
            elif verb=='messages':args='room_ref: str, after: str | None = None, limit: int | None = None'
            elif verb=='claim':args='room_ref: str, turn_ref: str'
            elif verb=='outcomes':args='handle: dict[str, Any]'
            elif verb=='list':args=''
            else:args='spec: dict[str, Any]'
            python_stub += f'    def {verb}(self'+(', '+args if args else '')+') -> Any: ...\n'
    files = {
        'crates/oneiron/src/task_verb/sdk_generated.rs':core,
        'crates/oneiron/src/task_verb/verb_catalog.rs':task_catalog,
        'crates/oneiron/src/workspace_roster/rooms/verb_catalog.rs':room_catalog,
        'crates/oneiron-server/src/mcp/agent_catalog.rs':mcp,
        'crates/oneiron-server/src/api/facade/agent_verbs.rs':server,
        'crates/oneiron-remote/src/agent_verbs.rs':remote,
        'crates/oneiron-napi/src/facade/client/agent_verbs.rs':napi,
        'packages/oneiron/src/agent-verbs.ts':ts,
        'crates/oneiron-py/python/oneiron/agent_verbs.py':python,
        'crates/oneiron-py/python/oneiron/agent_verbs.pyi':python_stub,
    }
    for path, start, end, body in [
        ('crates/oneiron-py/src/lib.rs', '// BEGIN GENERATED AGENT VERBS', '// END GENERATED AGENT VERBS', py),
        ('packages/oneiron/src/native.ts', '// BEGIN GENERATED AGENT VERBS', '// END GENERATED AGENT VERBS', ts_native),
    ]:
        text=(ROOT/path).read_text()
        a=text.index(start)+len(start); b=text.index(end,a)
        files[path]=text[:a]+'\n'+body+'\n'+text[b:]
    for path, text in list(files.items()):
        if path.endswith('.rs'):
            result = subprocess.run(['rustfmt', '--edition', '2024', '--emit', 'stdout'], input=text, text=True, capture_output=True, cwd=ROOT, check=True)
            files[path] = result.stdout
    return files

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    stale=[]
    for path,text in outputs().items():
        p=ROOT/path
        if p.exists() and p.read_text()==text:continue
        stale.append(path)
        if not args.check:
            p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
    if args.check and stale:
        raise SystemExit('SDK-GENERATED-STALE: '+', '.join(stale))
if __name__=='__main__': main()
