// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
use super::*;
#[napi]
impl NativeClient {
    #[napi]
    pub fn tasks_ack(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.ack", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_cancel(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.cancel", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_check(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.check", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_create(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.create", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_expand(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.expand", input)
            .map_err(facade_error)
    }

    /// Witnesses one conversational turn.
    #[napi]
    pub fn witness(&self, turn: NapiWitnessTurnInput) -> napi::Result<NapiWitnessReceipt> {
        let stamped = oneiron_remote::stamp_occurred_at(turn.occurred_at).map_err(facade_error)?;
        // Caller numbers are already validated; narrowing failure here is
        // an internal invariant failure, not bad input.
        let occurred_at = i64::try_from(stamped)
            .map_err(|_| boundary_error("occurred_at is out of range".to_owned()))?;
        let turn = NapiWitnessTurn {
            conversation_ref: turn.conversation_ref,
            turn_ref: turn.turn_ref,
            messages: turn.messages,
            occurred_at,
        };
        let engine_turn = witness_turn_to_engine(&turn).map_err(witness_input_error)?;
        let receipt = self.inner.witness(&engine_turn).map_err(facade_error)?;
        Ok(witness_receipt_from_engine(receipt))
    }

    /// Upserts one claim through the gated claim-candidate path.
    #[napi]
    pub fn claim_upsert(&self, claim: NapiClaimInput) -> napi::Result<NapiCommitReceipt> {
        let engine_claim = claim_input_to_engine(&claim).map_err(facade_error)?;
        let receipt = self
            .inner
            .claim_upsert(&engine_claim)
            .map_err(facade_error)?;
        Ok(commit_receipt_from_engine(receipt))
    }

    /// Effort-dialed retrieval into a memory pack.
    #[napi]
    pub fn recall(
        &self,
        query: String,
        effort: Option<String>,
        scope: Option<NapiRecallScope>,
        limit: Option<f64>,
        format: Option<String>,
    ) -> napi::Result<NapiMemoryPack> {
        let effort = oneiron_remote::parse_effort(effort.as_deref().unwrap_or("medium"))
            .map_err(facade_error)?;
        let scope = recall_scope_to_engine(scope);
        let limit = limit
            .map(limit_to_engine)
            .transpose()
            .map_err(facade_error)?
            .unwrap_or(oneiron_remote::DEFAULT_RECALL_LIMIT);
        let pack = self
            .inner
            .recall(&query, effort, &scope, limit, format.as_deref())
            .map_err(facade_error)?;
        memory_pack_from_engine(pack).map_err(boundary_error)
    }

    /// Gate decision receipts, newest first.
    #[napi]
    pub fn receipts(&self, limit: Option<f64>) -> napi::Result<Vec<NapiGateReceipt>> {
        let limit = limit
            .map(limit_to_engine)
            .transpose()
            .map_err(facade_error)?
            .unwrap_or(oneiron_remote::DEFAULT_RECEIPTS_LIMIT);
        let records = self.inner.receipts(limit).map_err(facade_error)?;
        records
            .into_iter()
            .map(|record| gate_receipt_from_engine(record).map_err(boundary_error))
            .collect()
    }
    #[napi]
    pub fn key_value_get(&self, request_json: String) -> napi::Result<String> {
        let input: serde_json::Value = serde_json::from_str(&request_json).map_err(|error| {
            facade_error(oneiron::memory::MemoryError {
                code: oneiron::memory::MEMORY_CODE_BAD_REQUEST.to_owned(),
                message: format!("invalid keyed request: {error}"),
                suggestions: vec!["Use the documented keyed DTO.".to_owned()],
                successor_short_id: None,
                gate_denial: None,
            })
        })?;
        let output = self
            .inner
            .agent_verb("key_value_get", input)
            .map_err(facade_error)?;
        serde_json::to_string(&output).map_err(|error| boundary_error(error.to_string()))
    }
    #[napi]
    pub fn key_value_put(&self, request_json: String) -> napi::Result<String> {
        let input: serde_json::Value = serde_json::from_str(&request_json).map_err(|error| {
            facade_error(oneiron::memory::MemoryError {
                code: oneiron::memory::MEMORY_CODE_BAD_REQUEST.to_owned(),
                message: format!("invalid keyed request: {error}"),
                suggestions: vec!["Use the documented keyed DTO.".to_owned()],
                successor_short_id: None,
                gate_denial: None,
            })
        })?;
        let output = self
            .inner
            .agent_verb("key_value_put", input)
            .map_err(facade_error)?;
        serde_json::to_string(&output).map_err(|error| boundary_error(error.to_string()))
    }
    #[napi]
    pub fn key_value_delete(&self, request_json: String) -> napi::Result<String> {
        let input: serde_json::Value = serde_json::from_str(&request_json).map_err(|error| {
            facade_error(oneiron::memory::MemoryError {
                code: oneiron::memory::MEMORY_CODE_BAD_REQUEST.to_owned(),
                message: format!("invalid keyed request: {error}"),
                suggestions: vec!["Use the documented keyed DTO.".to_owned()],
                successor_short_id: None,
                gate_denial: None,
            })
        })?;
        let output = self
            .inner
            .agent_verb("key_value_delete", input)
            .map_err(facade_error)?;
        serde_json::to_string(&output).map_err(|error| boundary_error(error.to_string()))
    }
    #[napi]
    pub fn key_value_search(&self, request_json: String) -> napi::Result<String> {
        let input: serde_json::Value = serde_json::from_str(&request_json).map_err(|error| {
            facade_error(oneiron::memory::MemoryError {
                code: oneiron::memory::MEMORY_CODE_BAD_REQUEST.to_owned(),
                message: format!("invalid keyed request: {error}"),
                suggestions: vec!["Use the documented keyed DTO.".to_owned()],
                successor_short_id: None,
                gate_denial: None,
            })
        })?;
        let output = self
            .inner
            .agent_verb("key_value_search", input)
            .map_err(facade_error)?;
        serde_json::to_string(&output).map_err(|error| boundary_error(error.to_string()))
    }
    #[napi]
    pub fn key_value_namespaces(&self, request_json: String) -> napi::Result<String> {
        let input: serde_json::Value = serde_json::from_str(&request_json).map_err(|error| {
            facade_error(oneiron::memory::MemoryError {
                code: oneiron::memory::MEMORY_CODE_BAD_REQUEST.to_owned(),
                message: format!("invalid keyed request: {error}"),
                suggestions: vec!["Use the documented keyed DTO.".to_owned()],
                successor_short_id: None,
                gate_denial: None,
            })
        })?;
        let output = self
            .inner
            .agent_verb("key_value_namespaces", input)
            .map_err(facade_error)?;
        serde_json::to_string(&output).map_err(|error| boundary_error(error.to_string()))
    }
    #[napi]
    pub fn tasks_ask(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.ask", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_wait(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.wait", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_answer(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.answer", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_outcomes(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.outcomes", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_list(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.list", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_messages(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.messages", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_claim(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.claim", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_speak(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.speak", input)
            .map_err(facade_error)
    }
}
