// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
use super::*;
#[napi]
impl NativeClient {
    #[napi]
    pub fn tasks_ask(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.ask", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_wait(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.wait", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_answer(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.answer", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn tasks_outcomes(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("tasks.outcomes", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_list(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.list", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_messages(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.messages", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_claim(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.claim", input)
            .map_err(facade_error)
    }
    #[napi]
    pub fn rooms_speak(&self, input: serde_json::Value) -> napi::Result<serde_json::Value> {
        self.inner
            .agent_verb("rooms.speak", input)
            .map_err(facade_error)
    }
}
