// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
/// The verb-table rows a code run answers itself, as the typed `self.*` call
/// each names: code mode serves them beside the host's rows, and no host door,
/// tool, route or binding carries them.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunVerb {
    Search,
    PutClaim,
    SupersedeClaim,
    PutEdge,
}
impl RunVerb {
    pub const ALL: &[Self] = &[
        Self::Search,
        Self::PutClaim,
        Self::SupersedeClaim,
        Self::PutEdge,
    ];
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|verb| verb.as_str() == name)
    }
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Search => "search",
            Self::PutClaim => "put_claim",
            Self::SupersedeClaim => "supersede_claim",
            Self::PutEdge => "put_edge",
        }
    }
    pub const fn writes(self) -> bool {
        matches!(self, Self::PutClaim | Self::SupersedeClaim | Self::PutEdge)
    }
    pub const fn effect(self) -> crate::code_run::SelfEffect {
        match self {
            Self::Search => crate::code_run::SelfEffect::MemorySearch,
            Self::PutClaim => crate::code_run::SelfEffect::MemoryPutClaim,
            Self::SupersedeClaim => crate::code_run::SelfEffect::MemorySupersedeClaim,
            Self::PutEdge => crate::code_run::SelfEffect::MemoryPutEdge,
        }
    }
}
