// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
pub const AGENT_VERBS: &[&str] = &[
    "witness",
    "claim_upsert",
    "recall",
    "receipts",
    "key_value_get",
    "key_value_put",
    "key_value_delete",
    "key_value_search",
    "key_value_namespaces",
    "tasks.ask",
    "tasks.wait",
    "tasks.answer",
    "tasks.outcomes",
    "rooms.list",
    "rooms.messages",
    "rooms.claim",
    "rooms.speak",
];
pub fn validate_input(verb: &str, value: &serde_json::Value) -> MemoryResult<()> {
    match verb {
        "witness" => {
            let input: crate::memory::WitnessTurn = decode(value.clone())?;
            crate::memory::caps::check_witness_turn(&input)?;
        }
        "claim_upsert" => {
            let input: crate::memory::ClaimInput = decode(value.clone())?;
            crate::memory::caps::check_claim_input(&input)?;
        }
        "recall" => {
            let input: RecallRequest = decode(value.clone())?;
            crate::memory::caps::check_query(&input.query)?;
            crate::memory::caps::check_limit(input.limit.unwrap_or(10))?;
        }
        "receipts" => {
            let input: ReceiptsRequest = decode(value.clone())?;
            crate::memory::caps::check_limit(input.limit.unwrap_or(100))?;
        }
        "key_value_get" => {
            let _input: crate::memory::KeyValueAddress = decode(value.clone())?;
        }
        "key_value_put" => {
            let _input: crate::memory::KeyValuePut = decode(value.clone())?;
        }
        "key_value_delete" => {
            let _input: crate::memory::KeyValueAddress = decode(value.clone())?;
        }
        "key_value_search" => {
            let _input: crate::memory::KeyValueSearch = decode(value.clone())?;
        }
        "key_value_namespaces" => {
            let _input: crate::memory::KeyValueNamespaces = decode(value.clone())?;
        }
        "tasks.ask" => {
            let _input: crate::task_verb::TaskAskSpec = decode(value.clone())?;
        }
        "tasks.wait" => {
            let _input: TaskWaitRequest = decode(value.clone())?;
        }
        "tasks.answer" => {
            let _input: TaskAnswerRequest = decode(value.clone())?;
        }
        "tasks.outcomes" => {
            let _input: crate::task_verb::TaskAskHandle = decode(value.clone())?;
        }
        "rooms.list" => {
            let _input: EmptyRequest = decode(value.clone())?;
        }
        "rooms.messages" => {
            let _input: RoomRequest = decode(value.clone())?;
        }
        "rooms.claim" => {
            let _input: RoomClaimRequest = decode(value.clone())?;
        }
        "rooms.speak" => {
            let _input: crate::memory::WitnessTurn = decode(value.clone())?;
        }
        _ => return Err(MemoryError::bad_request("unknown SDK agent verb")),
    }
    Ok(())
}
pub fn invoke(
    memory: &Memory<'_>,
    verb: &str,
    value: serde_json::Value,
) -> MemoryResult<serde_json::Value> {
    match verb {
        "witness" => encode(witness(memory, decode(value)?)?),
        "claim_upsert" => encode(claim_upsert(memory, decode(value)?)?),
        "recall" => encode(recall(memory, decode(value)?)?),
        "receipts" => encode(receipts(memory, decode(value)?)?),
        "key_value_get" => encode(key_value_get(memory, decode(value)?)?),
        "key_value_put" => encode(key_value_put(memory, decode(value)?)?),
        "key_value_delete" => encode(key_value_delete(memory, decode(value)?)?),
        "key_value_search" => encode(key_value_search(memory, decode(value)?)?),
        "key_value_namespaces" => encode(key_value_namespaces(memory, decode(value)?)?),
        "tasks.ask" => encode(tasks_ask(memory, decode(value)?)?),
        "tasks.wait" => encode(tasks_wait(memory, decode(value)?)?),
        "tasks.answer" => encode(tasks_answer(memory, decode(value)?)?),
        "tasks.outcomes" => encode(tasks_outcomes(memory, decode(value)?)?),
        "rooms.list" => encode(rooms_list(memory, decode(value)?)?),
        "rooms.messages" => encode(rooms_messages(memory, decode(value)?)?),
        "rooms.claim" => encode(rooms_claim(memory, decode(value)?)?),
        "rooms.speak" => encode(rooms_speak(memory, decode(value)?)?),
        _ => Err(MemoryError::bad_request("unknown SDK agent verb")),
    }
}
pub fn witness(
    memory: &Memory<'_>,
    input: crate::memory::WitnessTurn,
) -> MemoryResult<crate::memory::WitnessReceipt> {
    crate::memory::caps::check_witness_turn(&input)?;
    Ok(memory.witness(&input)?)
}
pub fn claim_upsert(
    memory: &Memory<'_>,
    input: crate::memory::ClaimInput,
) -> MemoryResult<crate::memory::CommitReceipt> {
    crate::memory::caps::check_claim_input(&input)?;
    Ok(memory.claim_upsert(&input)?)
}
pub fn recall(
    memory: &Memory<'_>,
    input: RecallRequest,
) -> MemoryResult<crate::memory::MemoryPack> {
    crate::memory::caps::check_query(&input.query)?;
    crate::memory::caps::check_limit(input.limit.unwrap_or(10))?;
    Ok(memory.recall(
        &input.query,
        input.effort.unwrap_or(crate::memory::Effort::Medium),
        &input.scope.unwrap_or_default(),
        input.limit.unwrap_or(10),
        input.format.as_deref(),
        None,
    )?)
}
pub fn receipts(
    memory: &Memory<'_>,
    input: ReceiptsRequest,
) -> MemoryResult<Vec<crate::memory::MemoryReceipt>> {
    crate::memory::caps::check_limit(input.limit.unwrap_or(100))?;
    Ok(memory.receipts(input.limit.unwrap_or(100))?)
}
pub fn key_value_get(
    memory: &Memory<'_>,
    input: crate::memory::KeyValueAddress,
) -> MemoryResult<Option<crate::memory::KeyValueItem>> {
    Ok(memory.key_value_get(&input)?)
}
pub fn key_value_put(
    memory: &Memory<'_>,
    input: crate::memory::KeyValuePut,
) -> MemoryResult<crate::memory::KeyValuePutReceipt> {
    Ok(memory.key_value_put(&input)?)
}
pub fn key_value_delete(
    memory: &Memory<'_>,
    input: crate::memory::KeyValueAddress,
) -> MemoryResult<crate::memory::KeyValueDeleteReceipt> {
    Ok(memory.key_value_delete(&input)?)
}
pub fn key_value_search(
    memory: &Memory<'_>,
    input: crate::memory::KeyValueSearch,
) -> MemoryResult<Vec<crate::memory::KeyValueItem>> {
    Ok(memory.key_value_search(&input)?)
}
pub fn key_value_namespaces(
    memory: &Memory<'_>,
    input: crate::memory::KeyValueNamespaces,
) -> MemoryResult<Vec<Vec<String>>> {
    Ok(memory.key_value_namespaces(&input)?)
}
pub fn tasks_ask(
    memory: &Memory<'_>,
    input: crate::task_verb::TaskAskSpec,
) -> MemoryResult<crate::task_verb::TaskAskReceipt> {
    Ok(memory.tasks_ask(&input)?)
}
pub fn tasks_wait(
    memory: &Memory<'_>,
    input: TaskWaitRequest,
) -> MemoryResult<crate::task_verb::TaskWaitOutcome> {
    Ok(memory.tasks_wait_external(&input.handle, &input.step_key)?)
}
pub fn tasks_answer(
    memory: &Memory<'_>,
    input: TaskAnswerRequest,
) -> MemoryResult<crate::task_verb::TaskAskAnswer> {
    Ok(memory.tasks_answer(&input.handle, crate::EntityId::from_hex(&input.result_ref)?)?)
}
pub fn tasks_outcomes(
    memory: &Memory<'_>,
    input: crate::task_verb::TaskAskHandle,
) -> MemoryResult<Vec<crate::llm::decision::questions::CalibrationPair>> {
    Ok(memory.tasks_ask_outcomes(&input)?)
}
pub fn rooms_list(
    memory: &Memory<'_>,
    _input: EmptyRequest,
) -> MemoryResult<Vec<crate::task_verb::sdk::RoomEntry>> {
    Ok(memory
        .rooms_list()?
        .into_iter()
        .map(|(id, room)| RoomEntry {
            id: id.to_hex(),
            room,
        })
        .collect::<Vec<_>>())
}
pub fn rooms_messages(
    memory: &Memory<'_>,
    input: RoomRequest,
) -> MemoryResult<crate::workspace_roster::RoomPage> {
    Ok(memory.rooms_messages_page(
        crate::EntityId::from_hex(&input.room_ref)?,
        input
            .after
            .as_deref()
            .map(crate::EntityId::from_hex)
            .transpose()?,
        input.limit.unwrap_or(256),
    )?)
}
pub fn rooms_claim(
    memory: &Memory<'_>,
    input: RoomClaimRequest,
) -> MemoryResult<crate::workspace_roster::RoomClaimOutcome> {
    Ok(memory.rooms_claim(
        crate::EntityId::from_hex(&input.room_ref)?,
        crate::EntityId::from_hex(&input.turn_ref)?,
        crate::unix_seconds_now(),
    )?)
}
pub fn rooms_speak(
    memory: &Memory<'_>,
    input: crate::memory::WitnessTurn,
) -> MemoryResult<crate::memory::WitnessReceipt> {
    Ok(memory.rooms_speak(&input)?)
}
