// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
pub const AGENT_VERBS: &[&str] = &[
    "witness",
    "claim_upsert",
    "recall",
    "receipts",
    "key_value_get",
    "key_value_put",
    "key_value_delete",
    "key_value_search",
    "key_value_namespaces",
    "tasks.ask",
    "tasks.wait",
    "tasks.answer",
    "tasks.outcomes",
    "rooms.list",
    "rooms.messages",
    "rooms.claim",
    "rooms.speak",
];
pub fn validate_input(verb: &str, value: &serde_json::Value) -> MemoryResult<()> {
    match verb {
        "witness" => {
            let input: crate::memory::WitnessTurn = decode(value.clone())?;
            crate::memory::caps::check_witness_turn(&input)?;
        }
        "claim_upsert" => {
            let input: crate::memory::ClaimInput = decode(value.clone())?;
            crate::memory::caps::check_claim_input(&input)?;
        }
        "recall" => {
            let input: RecallRequest = decode(value.clone())?;
            crate::memory::caps::check_query(&input.query)?;
            crate::memory::caps::check_limit(input.limit.unwrap_or(10))?;
        }
        "receipts" => {
            let input: ReceiptsRequest = decode(value.clone())?;
            crate::memory::caps::check_limit(input.limit.unwrap_or(100))?;
        }
        "key_value_get" => {
            let _input: crate::memory::KeyValueAddress = decode(value.clone())?;
        }
        "key_value_put" => {
            let _input: crate::memory::KeyValuePut = decode(value.clone())?;
        }
        "key_value_delete" => {
            let _input: crate::memory::KeyValueAddress = decode(value.clone())?;
        }
        "key_value_search" => {
            let _input: crate::memory::KeyValueSearch = decode(value.clone())?;
        }
        "key_value_namespaces" => {
            let _input: crate::memory::KeyValueNamespaces = decode(value.clone())?;
        }
        "tasks.ask" => {
            let _input: crate::task_verb::TaskAskSpec = decode(value.clone())?;
        }
        "tasks.wait" => {
            let _input: TaskWaitRequest = decode(value.clone())?;
        }
        "tasks.answer" => {
            let _input: TaskAnswerRequest = decode(value.clone())?;
        }
        "tasks.outcomes" => {
            let _input: crate::task_verb::TaskAskHandle = decode(value.clone())?;
        }
        "rooms.list" => {
            let _input: EmptyRequest = decode(value.clone())?;
        }
        "rooms.messages" => {
            let _input: RoomRequest = decode(value.clone())?;
        }
        "rooms.claim" => {
            let _input: RoomClaimRequest = decode(value.clone())?;
        }
        "rooms.speak" => {
            let _input: crate::memory::WitnessTurn = decode(value.clone())?;
        }
        _ => return Err(MemoryError::bad_request("unknown SDK agent verb")),
    }
    Ok(())
}
pub fn invoke(
    memory: &Memory<'_>,
    verb: &str,
    value: serde_json::Value,
) -> MemoryResult<serde_json::Value> {
    validate_input(verb, &value)?;
    match verb {
        "witness" => {
            let input: crate::memory::WitnessTurn = decode(value)?;
            let output: crate::memory::WitnessReceipt = memory.witness(&input)?;
            encode(output)
        }
        "claim_upsert" => {
            let input: crate::memory::ClaimInput = decode(value)?;
            let output: crate::memory::CommitReceipt = memory.claim_upsert(&input)?;
            encode(output)
        }
        "recall" => {
            let input: RecallRequest = decode(value)?;
            let output: crate::memory::MemoryPack = memory.recall(
                &input.query,
                input.effort.unwrap_or(crate::memory::Effort::Medium),
                &input.scope.unwrap_or_default(),
                input.limit.unwrap_or(10),
                input.format.as_deref(),
                None,
            )?;
            encode(output)
        }
        "receipts" => {
            let input: ReceiptsRequest = decode(value)?;
            let output: Vec<crate::memory::MemoryReceipt> =
                memory.receipts(input.limit.unwrap_or(100))?;
            encode(output)
        }
        "key_value_get" => {
            let input: crate::memory::KeyValueAddress = decode(value)?;
            let output: Option<crate::memory::KeyValueItem> = memory.key_value_get(&input)?;
            encode(output)
        }
        "key_value_put" => {
            let input: crate::memory::KeyValuePut = decode(value)?;
            let output: crate::memory::KeyValuePutReceipt = memory.key_value_put(&input)?;
            encode(output)
        }
        "key_value_delete" => {
            let input: crate::memory::KeyValueAddress = decode(value)?;
            let output: crate::memory::KeyValueDeleteReceipt = memory.key_value_delete(&input)?;
            encode(output)
        }
        "key_value_search" => {
            let input: crate::memory::KeyValueSearch = decode(value)?;
            let output: Vec<crate::memory::KeyValueItem> = memory.key_value_search(&input)?;
            encode(output)
        }
        "key_value_namespaces" => {
            let input: crate::memory::KeyValueNamespaces = decode(value)?;
            let output: Vec<Vec<String>> = memory.key_value_namespaces(&input)?;
            encode(output)
        }
        "tasks.ask" => {
            let input: crate::task_verb::TaskAskSpec = decode(value)?;
            let output: crate::task_verb::TaskAskReceipt = memory.tasks_ask(&input)?;
            encode(output)
        }
        "tasks.wait" => {
            let input: TaskWaitRequest = decode(value)?;
            let output: crate::task_verb::TaskWaitOutcome =
                memory.tasks_wait_external(&input.handle, &input.step_key)?;
            encode(output)
        }
        "tasks.answer" => {
            let input: TaskAnswerRequest = decode(value)?;
            let output: crate::task_verb::TaskAskAnswer = memory
                .tasks_answer(&input.handle, crate::EntityId::from_hex(&input.result_ref)?)?;
            encode(output)
        }
        "tasks.outcomes" => {
            let input: crate::task_verb::TaskAskHandle = decode(value)?;
            let output: Vec<crate::llm::decision::questions::CalibrationPair> =
                memory.tasks_ask_outcomes(&input)?;
            encode(output)
        }
        "rooms.list" => {
            let _input: EmptyRequest = decode(value)?;
            let output: Vec<crate::task_verb::sdk::RoomEntry> = memory
                .rooms_list()?
                .into_iter()
                .map(|(id, room)| RoomEntry {
                    id: id.to_hex(),
                    room,
                })
                .collect::<Vec<_>>();
            encode(output)
        }
        "rooms.messages" => {
            let input: RoomRequest = decode(value)?;
            let output: Vec<crate::workspace_roster::RoomTurn> = memory.rooms_messages_page(
                crate::EntityId::from_hex(&input.room_ref)?,
                input
                    .after
                    .as_deref()
                    .map(crate::EntityId::from_hex)
                    .transpose()?,
                input.limit.unwrap_or(256),
            )?;
            encode(output)
        }
        "rooms.claim" => {
            let input: RoomClaimRequest = decode(value)?;
            let output: crate::workspace_roster::RoomClaimOutcome = memory.rooms_claim(
                crate::EntityId::from_hex(&input.room_ref)?,
                crate::EntityId::from_hex(&input.turn_ref)?,
                crate::unix_seconds_now(),
            )?;
            encode(output)
        }
        "rooms.speak" => {
            let input: crate::memory::WitnessTurn = decode(value)?;
            let output: crate::memory::WitnessReceipt = memory.rooms_speak(&input)?;
            encode(output)
        }
        _ => Err(MemoryError::bad_request("unknown SDK agent verb")),
    }
}
