// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentVerb {
    BoardExpand,
    BoardRefresh,
    BoardSubscribe,
    BoardUnsubscribe,
    Cancel,
    Describe,
    TasksCreate,
    TasksUpdate,
    Witness,
    ClaimUpsert,
    Recall,
    Export,
    Receipts,
    KeyValueGet,
    KeyValuePut,
    KeyValueDelete,
    KeyValueSearch,
    KeyValueNamespaces,
    Can,
    Peek,
    TasksAsk,
    TasksWait,
    TasksAnswer,
    TasksOutcomes,
    RoomsList,
    RoomsMessages,
    RoomsRender,
    RoomsFind,
    RoomsGet,
    RoomsTrunk,
    RoomsClaim,
    RoomsSpeak,
}
impl AgentVerb {
    pub const ALL: &[Self] = &[
        Self::BoardExpand,
        Self::BoardRefresh,
        Self::BoardSubscribe,
        Self::BoardUnsubscribe,
        Self::Cancel,
        Self::Describe,
        Self::TasksCreate,
        Self::TasksUpdate,
        Self::Witness,
        Self::ClaimUpsert,
        Self::Recall,
        Self::Export,
        Self::Receipts,
        Self::KeyValueGet,
        Self::KeyValuePut,
        Self::KeyValueDelete,
        Self::KeyValueSearch,
        Self::KeyValueNamespaces,
        Self::Can,
        Self::Peek,
        Self::TasksAsk,
        Self::TasksWait,
        Self::TasksAnswer,
        Self::TasksOutcomes,
        Self::RoomsList,
        Self::RoomsMessages,
        Self::RoomsRender,
        Self::RoomsFind,
        Self::RoomsGet,
        Self::RoomsTrunk,
        Self::RoomsClaim,
        Self::RoomsSpeak,
    ];
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|verb| verb.as_str() == name)
    }
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BoardExpand => "board.expand",
            Self::BoardRefresh => "board.refresh",
            Self::BoardSubscribe => "board.subscribe",
            Self::BoardUnsubscribe => "board.unsubscribe",
            Self::Cancel => "cancel",
            Self::Describe => "describe",
            Self::TasksCreate => "tasks.create",
            Self::TasksUpdate => "tasks.update",
            Self::Witness => "witness",
            Self::ClaimUpsert => "claim_upsert",
            Self::Recall => "recall",
            Self::Export => "export",
            Self::Receipts => "receipts",
            Self::KeyValueGet => "key_value_get",
            Self::KeyValuePut => "key_value_put",
            Self::KeyValueDelete => "key_value_delete",
            Self::KeyValueSearch => "key_value_search",
            Self::KeyValueNamespaces => "key_value_namespaces",
            Self::Can => "can",
            Self::Peek => "peek",
            Self::TasksAsk => "tasks.ask",
            Self::TasksWait => "tasks.wait",
            Self::TasksAnswer => "tasks.answer",
            Self::TasksOutcomes => "tasks.outcomes",
            Self::RoomsList => "rooms.list",
            Self::RoomsMessages => "rooms.messages",
            Self::RoomsRender => "rooms.render",
            Self::RoomsFind => "rooms.find",
            Self::RoomsGet => "rooms.get",
            Self::RoomsTrunk => "rooms.trunk",
            Self::RoomsClaim => "rooms.claim",
            Self::RoomsSpeak => "rooms.speak",
        }
    }
    pub const fn is_facade(self) -> bool {
        matches!(
            self,
            Self::Cancel
                | Self::Describe
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::Witness
                | Self::ClaimUpsert
                | Self::Recall
                | Self::Export
                | Self::Receipts
                | Self::KeyValueGet
                | Self::KeyValuePut
                | Self::KeyValueDelete
                | Self::KeyValueSearch
                | Self::KeyValueNamespaces
                | Self::Can
                | Self::Peek
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
                | Self::RoomsRender
                | Self::RoomsFind
                | Self::RoomsGet
                | Self::RoomsTrunk
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn is_section(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::BoardRefresh
                | Self::BoardSubscribe
                | Self::BoardUnsubscribe
                | Self::Cancel
                | Self::Describe
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
        )
    }
    pub const fn continuable(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::Describe
                | Self::Receipts
                | Self::KeyValueSearch
                | Self::KeyValueNamespaces
                | Self::Peek
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
                | Self::RoomsRender
                | Self::RoomsFind
        )
    }
    pub const fn filtered_read(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::BoardRefresh
                | Self::BoardSubscribe
                | Self::BoardUnsubscribe
                | Self::Describe
        )
    }
    pub const fn requires_unscoped(self) -> bool {
        matches!(
            self,
            Self::TasksCreate
                | Self::Witness
                | Self::ClaimUpsert
                | Self::Recall
                | Self::Export
                | Self::Receipts
                | Self::KeyValueGet
                | Self::KeyValuePut
                | Self::KeyValueDelete
                | Self::KeyValueSearch
                | Self::KeyValueNamespaces
                | Self::Can
                | Self::Peek
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
                | Self::RoomsRender
                | Self::RoomsFind
                | Self::RoomsGet
                | Self::RoomsTrunk
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn writes(self) -> bool {
        matches!(
            self,
            Self::Cancel
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::Witness
                | Self::ClaimUpsert
                | Self::KeyValuePut
                | Self::KeyValueDelete
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn argument_fields(self) -> &'static [&'static str] {
        match self {
            Self::BoardExpand => &["key", "frame_epoch"],
            Self::BoardRefresh => &["frame_epoch"],
            Self::BoardSubscribe => &["scopes"],
            Self::BoardUnsubscribe => &["scopes"],
            Self::Cancel => &["task_ref"],
            Self::Describe => &["task_ref", "self", "session_id"],
            Self::TasksCreate => &["spec", "label"],
            Self::TasksUpdate => &["task_ref"],
            Self::Witness => &["spec"],
            Self::ClaimUpsert => &["spec"],
            Self::Recall => &["spec"],
            Self::Export => &["spec"],
            Self::Receipts => &["spec"],
            Self::KeyValueGet => &["spec"],
            Self::KeyValuePut => &["spec"],
            Self::KeyValueDelete => &["spec"],
            Self::KeyValueSearch => &["spec"],
            Self::KeyValueNamespaces => &["spec"],
            Self::Can => &["spec"],
            Self::Peek => &["spec"],
            Self::TasksAsk => &["spec"],
            Self::TasksWait => &["spec"],
            Self::TasksAnswer => &["spec"],
            Self::TasksOutcomes => &["spec"],
            Self::RoomsList => &[],
            Self::RoomsMessages => &["room_ref", "turn_ref"],
            Self::RoomsRender => &["room_ref"],
            Self::RoomsFind => &["room_ref", "turn_ref"],
            Self::RoomsGet => &["room_ref", "turn_ref"],
            Self::RoomsTrunk => &["room_ref", "turn_ref"],
            Self::RoomsClaim => &["room_ref", "turn_ref"],
            Self::RoomsSpeak => &["spec", "room_ref"],
        }
    }
    pub const fn required_fields(self) -> &'static [&'static str] {
        match self {
            Self::BoardExpand => &["key"],
            Self::BoardRefresh => &[],
            Self::BoardSubscribe => &["scopes"],
            Self::BoardUnsubscribe => &["scopes"],
            Self::Cancel => &["task_ref"],
            Self::Describe => &[],
            Self::TasksCreate => &["spec"],
            Self::TasksUpdate => &["task_ref"],
            Self::Witness => &["spec"],
            Self::ClaimUpsert => &["spec"],
            Self::Recall => &["spec"],
            Self::Export => &["spec"],
            Self::Receipts => &["spec"],
            Self::KeyValueGet => &["spec"],
            Self::KeyValuePut => &["spec"],
            Self::KeyValueDelete => &["spec"],
            Self::KeyValueSearch => &["spec"],
            Self::KeyValueNamespaces => &["spec"],
            Self::Can => &["spec"],
            Self::Peek => &["spec"],
            Self::TasksAsk => &["spec"],
            Self::TasksWait => &["spec"],
            Self::TasksAnswer => &["spec"],
            Self::TasksOutcomes => &["spec"],
            Self::RoomsList => &[],
            Self::RoomsMessages => &["room_ref"],
            Self::RoomsRender => &["room_ref"],
            Self::RoomsFind => &["room_ref"],
            Self::RoomsGet => &["room_ref", "turn_ref"],
            Self::RoomsTrunk => &["room_ref", "turn_ref"],
            Self::RoomsClaim => &["room_ref", "turn_ref"],
            Self::RoomsSpeak => &["spec", "room_ref"],
        }
    }
}
