// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
pub const TASKS_VERBS: [&str; 9] = [
    "tasks.ack",
    "tasks.answer",
    "tasks.ask",
    "tasks.cancel",
    "tasks.check",
    "tasks.create",
    "tasks.expand",
    "tasks.outcomes",
    "tasks.wait",
];
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TasksVerb {
    Ack,
    Answer,
    Ask,
    Cancel,
    Check,
    Create,
    Expand,
    Outcomes,
    Wait,
}
impl TasksVerb {
    pub const ALL: [Self; 9] = [
        Self::Ack,
        Self::Answer,
        Self::Ask,
        Self::Cancel,
        Self::Check,
        Self::Create,
        Self::Expand,
        Self::Outcomes,
        Self::Wait,
    ];
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ack => "tasks.ack",
            Self::Answer => "tasks.answer",
            Self::Ask => "tasks.ask",
            Self::Cancel => "tasks.cancel",
            Self::Check => "tasks.check",
            Self::Create => "tasks.create",
            Self::Expand => "tasks.expand",
            Self::Outcomes => "tasks.outcomes",
            Self::Wait => "tasks.wait",
        }
    }
}
