// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentVerb {
    BoardExpand,
    BoardRefresh,
    BoardSubscribe,
    BoardUnsubscribe,
    Cancel,
    Describe,
    TasksCreate,
    TasksUpdate,
    Witness,
    ClaimUpsert,
    Recall,
    Receipts,
    KeyValueGet,
    KeyValuePut,
    KeyValueDelete,
    KeyValueSearch,
    KeyValueNamespaces,
    Can,
    Peek,
    TasksAsk,
    TasksWait,
    TasksAnswer,
    TasksOutcomes,
    RoomsList,
    RoomsMessages,
    RoomsClaim,
    RoomsSpeak,
}
impl AgentVerb {
    pub const ALL: &[Self] = &[
        Self::BoardExpand,
        Self::BoardRefresh,
        Self::BoardSubscribe,
        Self::BoardUnsubscribe,
        Self::Cancel,
        Self::Describe,
        Self::TasksCreate,
        Self::TasksUpdate,
        Self::Witness,
        Self::ClaimUpsert,
        Self::Recall,
        Self::Receipts,
        Self::KeyValueGet,
        Self::KeyValuePut,
        Self::KeyValueDelete,
        Self::KeyValueSearch,
        Self::KeyValueNamespaces,
        Self::Can,
        Self::Peek,
        Self::TasksAsk,
        Self::TasksWait,
        Self::TasksAnswer,
        Self::TasksOutcomes,
        Self::RoomsList,
        Self::RoomsMessages,
        Self::RoomsClaim,
        Self::RoomsSpeak,
    ];
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|verb| verb.as_str() == name)
    }
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BoardExpand => "board.expand",
            Self::BoardRefresh => "board.refresh",
            Self::BoardSubscribe => "board.subscribe",
            Self::BoardUnsubscribe => "board.unsubscribe",
            Self::Cancel => "cancel",
            Self::Describe => "describe",
            Self::TasksCreate => "tasks.create",
            Self::TasksUpdate => "tasks.update",
            Self::Witness => "witness",
            Self::ClaimUpsert => "claim_upsert",
            Self::Recall => "recall",
            Self::Receipts => "receipts",
            Self::KeyValueGet => "key_value_get",
            Self::KeyValuePut => "key_value_put",
            Self::KeyValueDelete => "key_value_delete",
            Self::KeyValueSearch => "key_value_search",
            Self::KeyValueNamespaces => "key_value_namespaces",
            Self::Can => "can",
            Self::Peek => "peek",
            Self::TasksAsk => "tasks.ask",
            Self::TasksWait => "tasks.wait",
            Self::TasksAnswer => "tasks.answer",
            Self::TasksOutcomes => "tasks.outcomes",
            Self::RoomsList => "rooms.list",
            Self::RoomsMessages => "rooms.messages",
            Self::RoomsClaim => "rooms.claim",
            Self::RoomsSpeak => "rooms.speak",
        }
    }
    pub const fn is_facade(self) -> bool {
        matches!(
            self,
            Self::Cancel
                | Self::Describe
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::Witness
                | Self::ClaimUpsert
                | Self::Recall
                | Self::Receipts
                | Self::KeyValueGet
                | Self::KeyValuePut
                | Self::KeyValueDelete
                | Self::KeyValueSearch
                | Self::KeyValueNamespaces
                | Self::Can
                | Self::Peek
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn is_section(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::BoardRefresh
                | Self::BoardSubscribe
                | Self::BoardUnsubscribe
                | Self::Cancel
                | Self::Describe
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
        )
    }
    pub const fn is_mcp(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::BoardRefresh
                | Self::BoardSubscribe
                | Self::BoardUnsubscribe
                | Self::Cancel
                | Self::Describe
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn continuable(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::Describe
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
        )
    }
    pub const fn filtered_read(self) -> bool {
        matches!(
            self,
            Self::BoardExpand
                | Self::BoardRefresh
                | Self::BoardSubscribe
                | Self::BoardUnsubscribe
                | Self::Describe
        )
    }
    pub const fn requires_unscoped(self) -> bool {
        matches!(
            self,
            Self::TasksCreate
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::TasksOutcomes
                | Self::RoomsList
                | Self::RoomsMessages
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn writes(self) -> bool {
        matches!(
            self,
            Self::Cancel
                | Self::TasksCreate
                | Self::TasksUpdate
                | Self::Witness
                | Self::ClaimUpsert
                | Self::KeyValuePut
                | Self::KeyValueDelete
                | Self::TasksAsk
                | Self::TasksWait
                | Self::TasksAnswer
                | Self::RoomsClaim
                | Self::RoomsSpeak
        )
    }
    pub const fn argument_fields(self) -> Option<&'static [&'static str]> {
        match self {
            Self::BoardExpand => Some(&["key", "frame_epoch"]),
            Self::BoardRefresh => Some(&["frame_epoch"]),
            Self::BoardSubscribe => Some(&["scopes"]),
            Self::BoardUnsubscribe => Some(&["scopes"]),
            Self::Cancel => Some(&["task_ref"]),
            Self::Describe => Some(&["task_ref"]),
            Self::TasksCreate => Some(&["spec", "label"]),
            Self::TasksUpdate => Some(&["task_ref"]),
            Self::TasksAsk => Some(&["spec"]),
            Self::TasksWait => Some(&["spec"]),
            Self::TasksAnswer => Some(&["spec"]),
            Self::TasksOutcomes => Some(&["spec"]),
            Self::RoomsList => Some(&[]),
            Self::RoomsMessages => Some(&["room_ref", "turn_ref"]),
            Self::RoomsClaim => Some(&["room_ref", "turn_ref"]),
            Self::RoomsSpeak => Some(&["spec", "room_ref"]),
            _ => None,
        }
    }
    pub const fn required_fields(self) -> Option<&'static [&'static str]> {
        match self {
            Self::BoardExpand => Some(&["key"]),
            Self::BoardRefresh => Some(&[]),
            Self::BoardSubscribe => Some(&["scopes"]),
            Self::BoardUnsubscribe => Some(&["scopes"]),
            Self::Cancel => Some(&["task_ref"]),
            Self::Describe => Some(&[]),
            Self::TasksCreate => Some(&["spec"]),
            Self::TasksUpdate => Some(&["task_ref"]),
            Self::TasksAsk => Some(&["spec"]),
            Self::TasksWait => Some(&["spec"]),
            Self::TasksAnswer => Some(&["spec"]),
            Self::TasksOutcomes => Some(&["spec"]),
            Self::RoomsList => Some(&[]),
            Self::RoomsMessages => Some(&["room_ref"]),
            Self::RoomsClaim => Some(&["room_ref", "turn_ref"]),
            Self::RoomsSpeak => Some(&["spec", "room_ref"]),
            _ => None,
        }
    }
}
