//! OpenAPI ApiDoc registration for the HTTP API.

use super::{
    __path_annotate_turn_vad, __path_booking_agent_instructions, __path_booking_availability,
    __path_booking_book, __path_booking_cancel, __path_booking_reschedule,
    __path_companion_memory_reason, __path_context_board_hydrate, __path_core_batch,
    __path_core_batch_short_id_hydrate, __path_core_context_pack, __path_core_hydrate,
    __path_core_memory_timeline, __path_core_memory_verb, __path_core_query, __path_core_run_tree,
    __path_core_run_tree_intervene, __path_core_run_tree_observe,
    __path_create_companion_access_grant, __path_create_companion_register_record,
    __path_create_core_conversation, __path_create_core_conversation_turn, __path_discover,
    __path_end_companion_register_relationship, __path_get_companion_profile,
    __path_get_companion_register_record, __path_get_consumer_usage,
    __path_get_consumer_usage_details, __path_get_core_outbound_capability,
    __path_get_core_outbound_verb_contract, __path_get_core_surface_event, __path_get_core_turn,
    __path_get_edges, __path_get_entity, __path_get_usage_rollup, __path_health,
    __path_lease_revoke, __path_list_core_conversation_turns, __path_list_core_conversations,
    __path_list_core_outbound_capabilities, __path_openapi_json, __path_read_turn_vad_annotation,
    __path_record_usage_event, __path_refresh_companion_profile,
    __path_retire_companion_register_record, __path_revoke_companion_access_grant,
    __path_search_semantic, __path_search_text, __path_search_vector, __path_skills_pack,
    __path_submit_core_surface_event, __path_top_up_consumer,
    __path_update_companion_register_record, BoundContext, CompanionAccessGrantResponse,
    CompanionAccessGrantScopePayload, CompanionCreateAccessGrantRequest,
    CompanionEndRelationshipRequest, CompanionEndRelationshipResponse,
    CompanionGoodbyeArtifactHookPayload, CompanionProfileAccess, CompanionProfileConfidencePayload,
    CompanionProfileDriftAnchor, CompanionProfileNextAction, CompanionProfilePayload,
    CompanionProfileRefreshRequest, CompanionProfileResponse, CompanionProfileStaleReasonPayload,
    CompanionRegisterCreateRecordRequest, CompanionRegisterProvenancePayload,
    CompanionRegisterRecordPayload, CompanionRegisterRecordResponse,
    CompanionRegisterRelationshipRefPayload, CompanionRegisterRetireRecordRequest,
    CompanionRegisterScopePayload, CompanionRegisterSubjectPayload,
    CompanionRegisterUpdateRecordRequest, CompanionRevokeAccessGrantRequest, ContextBoardBudget,
    ContextBoardCompanionAssembly, ContextBoardCompanionControls, ContextBoardMemories,
    ContextBoardMemoriesBudget, ContextBoardMemoriesControls, ContextBoardMemoriesCursor,
    ContextBoardMemoriesSlotControls, ContextBoardMemoryRow, ContextBoardMemorySlot,
    ContextBoardMemorySource, ContextBoardNotification, ContextBoardRequest, ContextBoardResponse,
    ContextBoardSession, ContextBoardSessionControls, ContextBoardUnprocessedItem,
    ContextPackBudgetControls, ContextPackDepthControls, ContextPackPolicyControls,
    ContextPackRetrievalBudgetControls, ContextPackTimeControls, CoreBatchEntityInput,
    CoreBatchEntityResult, CoreBatchRequest, CoreBatchResponse, CoreBatchShortIdHydrateItem,
    CoreBatchShortIdHydrateRequest, CoreBatchShortIdHydrateResponse, CoreContextEdge,
    CoreContextEntity, CoreContextPackEvidence, CoreContextPackItemAccounting,
    CoreContextPackRequest, CoreContextPackResponse, CoreContextPackScoreComponent,
    CoreContextPackScoreEvidence, CoreContextPackState, CoreContextPackStateKind,
    CoreContextPackStateReason, CoreContextPackStats, CoreCreateEntityRequest,
    CoreCreateTurnRequest, CoreEntityWriteResponse, CoreHydrateDeletionMetadata,
    CoreHydrateDeletionReason, CoreHydrateDeletionSource, CoreHydrateRequest, CoreHydrateResponse,
    CoreHydrateStatus, CoreListQuery, CoreMemoryOperationKind, CoreMemoryTimelineRecord,
    CoreMemoryTimelineRecordState, CoreMemoryTimelineResponse, CoreMemoryVerbDeleteOutcome,
    CoreMemoryVerbDeleteReason, CoreMemoryVerbRequest, CoreMemoryVerbResponse, CoreQueryRequest,
    CoreRunTreeEvent, CoreRunTreeEventKind, CoreRunTreeFailure, CoreRunTreeInterventionEffect,
    CoreRunTreeInterventionKind, CoreRunTreeInterventionRequest, CoreRunTreeInterventionResponse,
    CoreRunTreeNode, CoreRunTreeQuery, CoreRunTreeRepair, CoreRunTreeResponse, CoreRunTreeStatus,
    CoreRunTreeTimestamps, CoreShortIdHydrateError, CoreShortIdHydrateErrorKind,
    CoreShortIdHydrateOutcome, CoreTextField, DiscoverResponse, DiscoveredEntity, EdgeResult,
    FeatureFlags, HealthResponse, LeaseRevokeRequest, LeaseRevokeResponse, MemoryReasonFormat,
    MemoryReasonRequest, MemoryReasonResponse, MemoryReasonSessionContext, MemoryReasonTrace,
    OutboundCapabilityDiscovery, OutboundConnectorManifestSummary, RateLimitStatus, SearchResult,
    SemanticSearchRequest, SkillPackDiscovery, SurfaceCounterpartyPayload, SurfaceEventAckResponse,
    SurfaceEventActionPayload, SurfaceEventHandoffStatePayload, SurfaceEventRejectionResponse,
    SurfaceEventSourcePayload, SurfaceEventStatusResponse, SurfaceEventSubmitRequest,
    SurfaceInteractionKindPayload, SurfaceSourceAppPayload, TextSearchQuery, TurnVadAnnotateQuery,
    TurnVadAnnotateRequest, TurnVadAnnotateResponse, TurnVadAnnotationSource, VadPayload,
    VectorSearchQuery,
};
use crate::error::{ApiError, ApiErrorDetails, ApiErrorEnvelope, ErrorCode};
use crate::projection::View;
use crate::protocol::{CountMode, PaginatedResponse, ResponseMeta};
use crate::runtime::{
    RuntimeMode, RuntimeProviderKind, RuntimeRole, RuntimeRoute, RuntimeRouteProvenance,
    RuntimeRouteReason, RuntimeRouteSource, RuntimeRouteState, RuntimeStatus,
};
use crate::usage::{
    ConsumerAllowanceState, ConsumerAllowanceWarning, ConsumerAllowanceWarningLevel, ConsumerTopUp,
    ConsumerTopUpRequest, ConsumerTopUpState, ConsumerUsageDetails, ConsumerUsageState, UsageEvent,
    UsageRecordResult, UsageRollup,
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        openapi_json,
        skills_pack,
        health,
        discover,
        search_vector,
        search_semantic,
        search_text,
        get_entity,
        get_edges,
        core_batch,
        core_query,
        core_hydrate,
        core_batch_short_id_hydrate,
        core_memory_timeline,
        core_memory_verb,
        list_core_outbound_capabilities,
        get_core_outbound_capability,
        get_core_outbound_verb_contract,
        core_context_pack,
        context_board_hydrate,
        core_run_tree,
        core_run_tree_observe,
        core_run_tree_intervene,
        submit_core_surface_event,
        get_core_surface_event,
        list_core_conversations,
        create_core_conversation,
        list_core_conversation_turns,
        create_core_conversation_turn,
        get_core_turn,
        annotate_turn_vad,
        read_turn_vad_annotation,
        booking_agent_instructions,
        booking_availability,
        booking_book,
        booking_reschedule,
        booking_cancel,
        create_companion_access_grant,
        revoke_companion_access_grant,
        get_companion_profile,
        refresh_companion_profile,
        create_companion_register_record,
        get_companion_register_record,
        update_companion_register_record,
        retire_companion_register_record,
        end_companion_register_relationship,
        companion_memory_reason,
        record_usage_event,
        get_usage_rollup,
        get_consumer_usage,
        get_consumer_usage_details,
        top_up_consumer,
        lease_revoke
    ),
    components(schemas(
        CountMode,
        PaginatedResponse<SearchResult>,
        ResponseMeta,
        View,
        HealthResponse,
        DiscoverResponse,
        SkillPackDiscovery,
        BoundContext,
        DiscoveredEntity,
        FeatureFlags,
        OutboundCapabilityDiscovery,
        OutboundConnectorManifestSummary,
        RateLimitStatus,
        RuntimeMode,
        RuntimeProviderKind,
        RuntimeRole,
        RuntimeRoute,
        RuntimeRouteProvenance,
        RuntimeRouteReason,
        RuntimeRouteSource,
        RuntimeRouteState,
        RuntimeStatus,
        ApiError,
        ApiErrorEnvelope,
        ApiErrorDetails,
        ErrorCode,
        VectorSearchQuery,
        SemanticSearchRequest,
        SearchResult,
        TextSearchQuery,
        EdgeResult,
        CoreBatchRequest,
        CoreBatchEntityInput,
        CoreBatchEntityResult,
        CoreBatchResponse,
        CoreRunTreeQuery,
        CoreRunTreeInterventionRequest,
        CoreRunTreeInterventionKind,
        CoreRunTreeInterventionResponse,
        CoreRunTreeInterventionEffect,
        CoreRunTreeResponse,
        CoreRunTreeNode,
        CoreRunTreeStatus,
        CoreRunTreeTimestamps,
        CoreRunTreeFailure,
        CoreRunTreeEvent,
        CoreRunTreeEventKind,
        CoreRunTreeRepair,
        SurfaceEventSubmitRequest,
        SurfaceEventSourcePayload,
        SurfaceSourceAppPayload,
        SurfaceEventActionPayload,
        SurfaceInteractionKindPayload,
        SurfaceCounterpartyPayload,
        SurfaceEventAckResponse,
        SurfaceEventRejectionResponse,
        SurfaceEventStatusResponse,
        SurfaceEventHandoffStatePayload,
        CoreTextField,
        CoreQueryRequest,
        CoreHydrateRequest,
        CoreHydrateResponse,
        CoreHydrateStatus,
        CoreHydrateDeletionMetadata,
        CoreHydrateDeletionSource,
        CoreHydrateDeletionReason,
        CoreBatchShortIdHydrateRequest,
        CoreBatchShortIdHydrateResponse,
        CoreBatchShortIdHydrateItem,
        CoreShortIdHydrateOutcome,
        CoreShortIdHydrateError,
        CoreShortIdHydrateErrorKind,
        CoreMemoryTimelineResponse,
        CoreMemoryTimelineRecord,
        CoreMemoryTimelineRecordState,
        CoreMemoryVerbRequest,
        CoreMemoryVerbResponse,
        CoreMemoryVerbDeleteOutcome,
        CoreMemoryVerbDeleteReason,
        CoreMemoryOperationKind,
        ContextPackDepthControls,
        ContextPackPolicyControls,
        ContextPackTimeControls,
        ContextPackRetrievalBudgetControls,
        ContextPackBudgetControls,
        ContextBoardMemoriesControls,
        ContextBoardMemoriesSlotControls,
        ContextBoardSessionControls,
        ContextBoardCompanionControls,
        CoreContextPackRequest,
        CoreContextPackResponse,
        ContextBoardCompanionAssembly,
        ContextBoardMemories,
        ContextBoardMemoriesBudget,
        ContextBoardMemoryRow,
        ContextBoardMemorySlot,
        ContextBoardMemorySource,
        ContextBoardMemoriesCursor,
        ContextBoardRequest,
        ContextBoardResponse,
        ContextBoardSession,
        ContextBoardNotification,
        ContextBoardUnprocessedItem,
        ContextBoardBudget,
        CoreContextEntity,
        CoreContextEdge,
        CoreContextPackStats,
        CoreContextPackItemAccounting,
        CoreContextPackState,
        CoreContextPackStateKind,
        CoreContextPackStateReason,
        CoreContextPackScoreComponent,
        CoreContextPackScoreEvidence,
        CoreContextPackEvidence,
        CoreListQuery,
        CoreCreateEntityRequest,
        CoreCreateTurnRequest,
        CoreEntityWriteResponse,
        VadPayload,
        TurnVadAnnotationSource,
        TurnVadAnnotateRequest,
        TurnVadAnnotateQuery,
        TurnVadAnnotateResponse,
        CompanionAccessGrantScopePayload,
        CompanionAccessGrantResponse,
        CompanionCreateAccessGrantRequest,
        CompanionRevokeAccessGrantRequest,
        CompanionProfileAccess,
        CompanionProfileConfidencePayload,
        CompanionProfileDriftAnchor,
        CompanionProfileNextAction,
        CompanionProfilePayload,
        CompanionProfileRefreshRequest,
        CompanionProfileResponse,
        CompanionProfileStaleReasonPayload,
        CompanionRegisterScopePayload,
        CompanionRegisterRelationshipRefPayload,
        CompanionRegisterSubjectPayload,
        CompanionRegisterProvenancePayload,
        CompanionRegisterRecordPayload,
        CompanionRegisterCreateRecordRequest,
        CompanionRegisterUpdateRecordRequest,
        CompanionRegisterRetireRecordRequest,
        CompanionEndRelationshipRequest,
        CompanionGoodbyeArtifactHookPayload,
        CompanionEndRelationshipResponse,
        CompanionRegisterRecordResponse,
        MemoryReasonRequest,
        MemoryReasonResponse,
        MemoryReasonFormat,
        MemoryReasonSessionContext,
        MemoryReasonTrace,
        LeaseRevokeRequest,
        LeaseRevokeResponse,
        ConsumerAllowanceState,
        ConsumerAllowanceWarning,
        ConsumerAllowanceWarningLevel,
        ConsumerTopUp,
        ConsumerTopUpRequest,
        ConsumerTopUpState,
        ConsumerUsageDetails,
        ConsumerUsageState,
        UsageEvent,
        UsageRecordResult,
        UsageRollup
    )),
    info(
        title = "Oneiron Server API",
        version = "0.1.0",
        description = "Local Oneiron sync daemon HTTP API for search, entity reads, context-pack requests, and lease recovery."
    )
)]
pub(crate) struct ApiDoc;
