[files]
extend-exclude = [
    "docs/**/*.svg",
    "target/**",
    "**/*.lock",
]

[default.extend-words]
anc = "anc"
ba = "ba"
Caf = "Caf"
caf = "caf"
Flate = "Flate"
flate = "flate"
mis = "mis"
SINIC = "SINIC"
unparseable = "unparseable"
