// Generated by scripts/sdk/generate.py from the engine typed verb table.
export const FACADE_CATALOG = [
  {
    "wire": "witness",
    "sdk": "witness",
    "scope": "write",
    "request": "WitnessTurn",
    "response": "WitnessReceipt",
    "doc": "Witnesses one conversational turn."
  },
  {
    "wire": "commit",
    "sdk": "commit",
    "scope": "write",
    "request": "CommitRequest",
    "response": "Vec<CommitReceipt>",
    "doc": "Commits claims, one individually gated write per element."
  },
  {
    "wire": "claim_upsert",
    "sdk": "claimUpsert",
    "scope": "write",
    "request": "ClaimInput",
    "response": "CommitReceipt",
    "doc": "Upserts one claim with single-cardinality auto-supersede."
  },
  {
    "wire": "remember",
    "sdk": "remember",
    "scope": "write",
    "request": "ClaimInput",
    "response": "CommitReceipt",
    "doc": "Typed remember: claimUpsert with auto-supersede."
  },
  {
    "wire": "claim_retract",
    "sdk": "claimRetract",
    "scope": "write",
    "request": "ClaimRefRequest",
    "response": "CommitReceipt",
    "doc": "Retracts an active claim by ref."
  },
  {
    "wire": "forget",
    "sdk": "forget",
    "scope": "write",
    "request": "ForgetSelector",
    "response": "Vec<CommitReceipt>",
    "doc": "Typed forget: retract-with-receipt by short ref or subject+predicate."
  },
  {
    "wire": "claim_list",
    "sdk": "claimList",
    "scope": "read",
    "request": "ClaimListFilter",
    "response": "Vec<ClaimView>",
    "doc": "Lists claims by subject/predicate/lifecycle, bounded by limit."
  },
  {
    "wire": "claim_history",
    "sdk": "claimHistory",
    "scope": "read",
    "request": "ClaimRefRequest",
    "response": "Vec<ClaimView>",
    "doc": "Supersession timeline for one claim, oldest first."
  },
  {
    "wire": "safe_delete",
    "sdk": "safeDelete",
    "scope": "write",
    "request": "SafeDeleteRequest",
    "response": "DeleteReceipt",
    "doc": "Deletes an entity under a named reason, with a receipt."
  },
  {
    "wire": "pending_writes",
    "sdk": "pendingWrites",
    "scope": "read",
    "request": "LimitRequest",
    "response": "Vec<PendingWrite>",
    "doc": "Pending gated writes awaiting consent."
  },
  {
    "wire": "receipts",
    "sdk": "receipts",
    "scope": "read",
    "request": "LimitRequest",
    "response": "Vec<MemoryReceipt>",
    "doc": "Gate decision receipts, newest first."
  },
  {
    "wire": "hydrate",
    "sdk": "hydrate",
    "scope": "read",
    "request": "HydrateRequest",
    "response": "Vec<EntityView>",
    "doc": "Reads entities as typed views."
  },
  {
    "wire": "get_entity",
    "sdk": "getEntity",
    "scope": "read",
    "request": "EntityRefRequest",
    "response": "Option<EntityView>",
    "doc": "Reads one entity as a typed view."
  },
  {
    "wire": "query_bm25",
    "sdk": "queryBm25",
    "scope": "read",
    "request": "QueryRequest",
    "response": "Vec<LexicalHit>",
    "doc": "BM25 text search, engine-scored."
  },
  {
    "wire": "neighbors",
    "sdk": "neighbors",
    "scope": "read",
    "request": "NeighborsRequest",
    "response": "Vec<NeighborHit>",
    "doc": "Bounded graph neighborhood of one entity."
  },
  {
    "wire": "recall_view",
    "sdk": "recallView",
    "scope": "read",
    "request": "RecallViewRequest",
    "response": "MemoryPack",
    "doc": "Minimal recall for an exact-world view, with kind/predicate narrowing."
  },
  {
    "wire": "recall",
    "sdk": "recall",
    "scope": "read",
    "request": "RecallRequestDto",
    "response": "MemoryPack",
    "doc": "Effort-dialed retrieval into a memory pack."
  },
  {
    "wire": "put_structural",
    "sdk": "putStructural",
    "scope": "write",
    "request": "StructuralPutInput",
    "response": "EntityRefReceipt",
    "doc": "Structural create carrying text-index fields and edges."
  },
  {
    "wire": "put_habit_checkin",
    "sdk": "putHabitCheckin",
    "scope": "write",
    "request": "HabitCheckinInput",
    "response": "EntityRefReceipt",
    "doc": "Appends one habit check-in child."
  },
  {
    "wire": "put_companion_record",
    "sdk": "putCompanionRecord",
    "scope": "write",
    "request": "CompanionRecordInput",
    "response": "EntityRefReceipt",
    "doc": "Registers a companion persona record."
  },
  {
    "wire": "admit_imported_claim",
    "sdk": "admitImportedClaim",
    "scope": "write",
    "request": "AdmitImportedClaimInput",
    "response": "CommitReceipt",
    "doc": "Admits one imported-evidence claim (typed receipt)."
  },
  {
    "wire": "put_blob_artifact",
    "sdk": "putBlobArtifact",
    "scope": "write",
    "request": "BlobArtifactInput",
    "response": "EntityRefReceipt",
    "doc": "Registers one blob artifact."
  },
  {
    "wire": "append_blob_version",
    "sdk": "appendBlobVersion",
    "scope": "write",
    "request": "AppendBlobVersionRequest",
    "response": "BlobVersionView",
    "doc": "Appends one blob artifact version (base64 bytes)."
  },
  {
    "wire": "read_blob_version",
    "sdk": "readBlobVersion",
    "scope": "read",
    "request": "ReadBlobVersionRequest",
    "response": "BlobBytesResponse",
    "doc": "Reads one blob artifact version (base64 bytes)."
  },
  {
    "wire": "author_take",
    "sdk": "authorTake",
    "scope": "write",
    "request": "AuthorTakeRequest",
    "response": "EntityRefReceipt",
    "doc": "Appends one attributed opinion-take note beside a target."
  },
  {
    "wire": "schedule_outbound",
    "sdk": "scheduleOutbound",
    "scope": "write",
    "request": "ScheduleOutboundRequest",
    "response": "OutboundIntentReceipt",
    "doc": "Schedules one connector-send task through the OF-327 chokepoint."
  },
  {
    "wire": "calendar_read",
    "sdk": "calendarRead",
    "scope": "read",
    "request": "CalendarReadRequest",
    "response": "Option<CalendarEventView>",
    "doc": "Reads one calendar event under the caller read scope."
  },
  {
    "wire": "calendar_search",
    "sdk": "calendarSearch",
    "scope": "read",
    "request": "CalendarSearchRequest",
    "response": "Vec<CalendarEventView>",
    "doc": "Searches calendar events under the caller read scope."
  },
  {
    "wire": "calendar_freebusy",
    "sdk": "calendarFreebusy",
    "scope": "read",
    "request": "CalendarFreebusyRequest",
    "response": "CalendarFreebusyDto",
    "doc": "Busy-only occupancy over a range, source-redacted."
  },
  {
    "wire": "calendar_invite",
    "sdk": "calendarInvite",
    "scope": "write",
    "request": "CalendarInviteSurfaceInput",
    "response": "OutboundIntentReceipt",
    "doc": "Schedules one iMIP-shaped calendar invite through the outbound gate."
  },
  {
    "wire": "enqueue_consolidation",
    "sdk": "enqueueConsolidation",
    "scope": "write",
    "request": "ConsolidationAttemptInput",
    "response": "DreamerAttemptRef",
    "doc": "Enqueues one Dreamer consolidation attempt."
  },
  {
    "wire": "dreamer_attempt_status",
    "sdk": "dreamerAttemptStatus",
    "scope": "read",
    "request": "JobRefRequest",
    "response": "Option<DreamerAttemptView>",
    "doc": "Poll-model view of one Dreamer attempt."
  },
  {
    "wire": "seed_claims",
    "sdk": "seedClaims",
    "scope": "write",
    "request": "CommitRequest",
    "response": "Vec<CommitReceipt>",
    "doc": "Seeds claims as proposed writes."
  },
  {
    "wire": "ask",
    "sdk": "ask",
    "scope": "read",
    "request": "AskRequest",
    "response": "ChatResponse",
    "doc": "Extractive minimal-depth answer over ranked recall (no composer)."
  },
  {
    "wire": "search",
    "sdk": "search",
    "scope": "read",
    "request": "SearchRequest",
    "response": "Vec<SearchHit>",
    "doc": "Typed SDK stub-documentation search over this verb table."
  },
  {
    "wire": "execute",
    "sdk": "execute",
    "scope": "read",
    "request": "ExecuteRequest",
    "response": "ExecuteResponse",
    "doc": "Evaluates a bounded typed read program in one host call."
  },
  {
    "wire": "grant_artifact_publish",
    "sdk": "grantArtifactPublish",
    "scope": "write",
    "request": "GrantArtifactPublishRequest",
    "response": "GrantArtifactPublishResponse",
    "doc": "Grants an actor auto-publish on one artifact."
  },
  {
    "wire": "approve_gmail_message",
    "sdk": "approveGmailMessage",
    "scope": "write",
    "request": "ApproveGmailMessageRequest",
    "response": "UnitResponse",
    "doc": "Records one human per-message approval for a delegated Gmail send."
  },
  {
    "wire": "record_emergency_instruction",
    "sdk": "recordEmergencyInstruction",
    "scope": "write",
    "request": "EmergencyInstructionInput",
    "response": "crate::booking::emergency_reschedule::OwnerInstructionRecord",
    "doc": "Logs the lane-owned emergency stamp under the owner-verb checks."
  },
  {
    "wire": "query",
    "sdk": "query",
    "scope": "read",
    "request": "CoreQueryRequest",
    "response": "CoreQueryResponse",
    "doc": "Executes one actor-scoped query plan."
  },
  {
    "wire": "context_pack",
    "sdk": "contextPack",
    "scope": "read",
    "request": "CoreContextPackRequest",
    "response": "CoreContextPackResponse",
    "doc": "Executes one actor-scoped context-pack plan."
  },
  {
    "wire": "campaign_create",
    "sdk": "campaignCreate",
    "scope": "write",
    "request": "CampaignCreateRequest",
    "response": "CampaignRecordDto",
    "doc": "Creates one owner-bound Campaign record or membership page."
  },
  {
    "wire": "campaign_read",
    "sdk": "campaignRead",
    "scope": "read",
    "request": "CampaignRefRequest",
    "response": "RecordLookup<CampaignRecordDto>",
    "doc": "Reads one owner-bound Campaign record or membership page."
  },
  {
    "wire": "campaign_update",
    "sdk": "campaignUpdate",
    "scope": "write",
    "request": "CampaignUpdateRequest",
    "response": "CampaignRecordDto",
    "doc": "Updates one owner-bound Campaign record or membership page."
  },
  {
    "wire": "campaign_archive",
    "sdk": "campaignArchive",
    "scope": "write",
    "request": "CampaignArchiveRequest",
    "response": "CampaignRecordDto",
    "doc": "Archives one owner-bound Campaign record or membership page."
  },
  {
    "wire": "campaign_members",
    "sdk": "campaignMembers",
    "scope": "read",
    "request": "CampaignMembersRequest",
    "response": "MembershipPageDto",
    "doc": "Lists members of one owner-bound Campaign record or membership page."
  },
  {
    "wire": "saved_query_create",
    "sdk": "savedQueryCreate",
    "scope": "write",
    "request": "SavedQueryCreateRequest",
    "response": "SavedQueryRecordDto",
    "doc": "Creates one owner-bound SavedQuery record or membership page."
  },
  {
    "wire": "saved_query_read",
    "sdk": "savedQueryRead",
    "scope": "read",
    "request": "SavedQueryRefRequest",
    "response": "RecordLookup<SavedQueryRecordDto>",
    "doc": "Reads one owner-bound SavedQuery record or membership page."
  },
  {
    "wire": "saved_query_update",
    "sdk": "savedQueryUpdate",
    "scope": "write",
    "request": "SavedQueryUpdateRequest",
    "response": "SavedQueryRecordDto",
    "doc": "Updates one owner-bound SavedQuery record or membership page."
  },
  {
    "wire": "saved_query_archive",
    "sdk": "savedQueryArchive",
    "scope": "write",
    "request": "SavedQueryArchiveRequest",
    "response": "SavedQueryRecordDto",
    "doc": "Archives one owner-bound SavedQuery record or membership page."
  },
  {
    "wire": "saved_query_members",
    "sdk": "savedQueryMembers",
    "scope": "read",
    "request": "SavedQueryMembersRequest",
    "response": "MembershipPageDto",
    "doc": "Lists members of one owner-bound SavedQuery record or membership page."
  },
  {
    "wire": "set_expression_preference",
    "sdk": "setExpressionPreference",
    "scope": "write",
    "request": "SetExpressionPreferenceRequest",
    "response": "ExpressionPreferenceReceiptDto",
    "doc": "Writes a typed expression preference with full supersession receipts."
  },
  {
    "wire": "retract_expression_preference",
    "sdk": "retractExpressionPreference",
    "scope": "write",
    "request": "ClaimRefRequest",
    "response": "UnitResponse",
    "doc": "Retracts a preference and restores its eligible predecessor."
  },
  {
    "wire": "expression_preferences",
    "sdk": "expressionPreferences",
    "scope": "read",
    "request": "ExpressionPreferencesRequest",
    "response": "ExpressionPreferenceViewDto",
    "doc": "Reads preferences in force for a subject at an instant."
  },
  {
    "wire": "plan_emergency_reschedule",
    "sdk": "planEmergencyReschedule",
    "scope": "write",
    "request": "PlanEmergencyRescheduleRequest",
    "response": "EmergencyBatchPlanDto",
    "doc": "Persists an owner-authorized emergency rescheduling plan."
  },
  {
    "wire": "schedule_outbound_with_context",
    "sdk": "scheduleOutboundWithContext",
    "scope": "write",
    "request": "ScheduleOutboundRequest",
    "response": "OutboundIntentReceipt",
    "doc": "Schedules an outbound draft with explicit host timing context."
  },
  {
    "wire": "react_to_message",
    "sdk": "reactToMessage",
    "scope": "write",
    "request": "ReactToMessageInput",
    "response": "ReactionReceipt",
    "doc": "Toggles one glyph as the verified actor on a readable message."
  },
  {
    "wire": "reaction_pills",
    "sdk": "reactionPills",
    "scope": "read",
    "request": "ReactionPillsRequest",
    "response": "Vec<crate::conversation::reaction::ReactionGrouping>",
    "doc": "Reads grouped reactions for at most 50 messages in one batched read."
  },
  {
    "wire": "reactions_since",
    "sdk": "reactionsSince",
    "scope": "read",
    "request": "ReactionsSinceRequest",
    "response": "Vec<crate::conversation::reaction::ReactionSignal>",
    "doc": "Reads the bound person's reaction signals since a timestamp."
  },
  {
    "wire": "reactions_outbound",
    "sdk": "reactionsOutbound",
    "scope": "read",
    "request": "EntityRefRequest",
    "response": "crate::conversation::reaction::ReactionsOutbound",
    "doc": "Reads a room's capability-derived reaction outbound posture."
  },
  {
    "wire": "ingest_mirrored_reaction",
    "sdk": "ingestMirroredReaction",
    "scope": "write",
    "request": "MirroredReactionRequest",
    "response": "ReactionReceipt",
    "doc": "System-adapter-only idempotent mirrored reaction ingestion."
  },
  {
    "wire": "artifact_birth",
    "sdk": "artifactBirth",
    "scope": "read",
    "request": "EntityRefRequest",
    "response": "Option<ArtifactBirthView>",
    "doc": "Reads an artifact's immutable task/run/skill/input provenance."
  },
  {
    "wire": "artifacts_born_from",
    "sdk": "artifactsBornFrom",
    "scope": "read",
    "request": "ArtifactsBornFromRequest",
    "response": "Vec<ArtifactBirthView>",
    "doc": "Lists bounded artifact outputs of a task, run, skill or ask from the same ledger."
  }
] as const;
export type FacadeWireName = (typeof FACADE_CATALOG)[number]["wire"];
export type FacadeSdkName = (typeof FACADE_CATALOG)[number]["sdk"];
