// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
use super::*;
impl OneironClient {
    pub fn agent_verb(
        &self,
        verb: &str,
        input: serde_json::Value,
    ) -> Result<serde_json::Value, MemoryError> {
        self.ensure_dispatch_pid()?;
        if !oneiron::task_verb::sdk::AgentVerb::from_name(verb)
            .is_some_and(oneiron::task_verb::sdk::AgentVerb::is_facade)
        {
            return Err(crate::error::bad_request(
                "unknown SDK agent verb",
                &["Use a verb from the SDK catalog."],
            ));
        }
        oneiron::task_verb::sdk::validate_input(verb, &input)?;
        match &self.backend {
            Backend::Embedded(client) => {
                oneiron::task_verb::sdk::invoke(&client.memory(), verb, input)
            }
            Backend::Remote(client) => client.call(verb, &input),
        }
    }
    /// Cancels one task under the ladder's `auto` default. The receipt says
    /// what stopped and what became a proposal instead.
    pub fn cancel(
        &self,
        task_ref: &str,
    ) -> Result<oneiron::task_verb::TaskCancelReceipt, MemoryError> {
        let input = oneiron::task_verb::sdk::TaskRequest {
            task_ref: task_ref.to_owned(),
        };
        let value = serde_json::to_value(&input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("cancel", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Describes one task's card, or the whole TASKS section when no task is
    /// named.
    pub fn describe(
        &self,
        task_ref: Option<&str>,
    ) -> Result<oneiron::task_verb::TaskDescription, MemoryError> {
        let input = oneiron::task_verb::sdk::DescribeRequest {
            task_ref: task_ref.map(str::to_owned),
        };
        let value = serde_json::to_value(&input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("describe", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_create(
        &self,
        input: &oneiron::task_verb::sdk::TaskCreateRequest,
    ) -> Result<oneiron::task_verb::TaskCreateReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.create", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_update(
        &self,
        input: &oneiron::task_verb::sdk::TaskRequest,
    ) -> Result<oneiron::task_verb::TaskUpdateReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.update", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Witnesses one conversational turn.
    ///
    /// `turn.occurred_at` is already stamped by the caller through
    /// [`stamp_occurred_at`], because the engine DTO's field is required and a
    /// backend cannot tell an omitted `0` from a deliberate one.
    pub fn witness(
        &self,
        turn: &oneiron::memory::WitnessTurn,
    ) -> Result<oneiron::memory::WitnessReceipt, MemoryError> {
        oneiron::memory::caps::check_witness_turn(turn)?;
        let value = serde_json::to_value(turn).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("witness", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Upserts one claim through the gated claim-candidate path.
    pub fn claim_upsert(
        &self,
        claim: &oneiron::memory::ClaimInput,
    ) -> Result<oneiron::memory::CommitReceipt, MemoryError> {
        oneiron::memory::caps::check_claim_input(claim)?;
        let value = serde_json::to_value(claim).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("claim_upsert", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Recalls a memory pack.
    ///
    /// The lease argument the engine takes is `None` and is NOT a client
    /// input: no lease issuer exists, and a bearer slip is not one. An
    /// `Effort::High` call therefore returns the engine's `LEASE_REQUIRED`
    /// through both backends, spelled identically.
    pub fn recall(
        &self,
        query: &str,
        effort: oneiron::memory::Effort,
        scope: &oneiron::memory::RecallScope,
        limit: usize,
        format: Option<&str>,
    ) -> Result<oneiron::memory::MemoryPack, MemoryError> {
        let input = oneiron::task_verb::sdk::RecallRequest {
            query: query.to_owned(),
            effort: Some(effort),
            scope: Some(scope.clone()),
            limit: Some(limit),
            format: format.map(str::to_owned),
        };
        oneiron::memory::caps::check_query(&input.query)?;
        oneiron::memory::caps::check_limit(input.limit.unwrap_or(10))?;
        let value = serde_json::to_value(&input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("recall", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Lists governance receipts, newest first.
    pub fn receipts(
        &self,
        limit: usize,
    ) -> Result<Vec<oneiron::memory::MemoryReceipt>, MemoryError> {
        let input = oneiron::task_verb::sdk::ReceiptsRequest { limit: Some(limit) };
        oneiron::memory::caps::check_limit(input.limit.unwrap_or(100))?;
        let value = serde_json::to_value(&input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("receipts", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.
    pub fn key_value_get(
        &self,
        input: &oneiron::memory::KeyValueAddress,
    ) -> Result<Option<oneiron::memory::KeyValueItem>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("key_value_get", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.
    pub fn key_value_put(
        &self,
        input: &oneiron::memory::KeyValuePut,
    ) -> Result<oneiron::memory::KeyValuePutReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("key_value_put", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.
    pub fn key_value_delete(
        &self,
        input: &oneiron::memory::KeyValueAddress,
    ) -> Result<oneiron::memory::KeyValueDeleteReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("key_value_delete", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.
    pub fn key_value_search(
        &self,
        input: &oneiron::memory::KeyValueSearch,
    ) -> Result<Vec<oneiron::memory::KeyValueItem>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("key_value_search", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    /// Actor-owned worldless keyed memory; identical embedded/remote semantics.
    pub fn key_value_namespaces(
        &self,
        input: &oneiron::memory::KeyValueNamespaces,
    ) -> Result<Vec<Vec<String>>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("key_value_namespaces", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_ask(
        &self,
        input: &oneiron::task_verb::TaskAskSpec,
    ) -> Result<oneiron::task_verb::TaskAskReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.ask", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_wait(
        &self,
        input: &oneiron::task_verb::sdk::TaskWaitRequest,
    ) -> Result<oneiron::task_verb::TaskAskWait, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.wait", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_answer(
        &self,
        input: &oneiron::task_verb::sdk::TaskAnswerRequest,
    ) -> Result<oneiron::task_verb::TaskAskAnswer, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.answer", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_outcomes(
        &self,
        input: &oneiron::task_verb::TaskAskHandle,
    ) -> Result<Vec<oneiron::llm::decision::questions::CalibrationPair>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.outcomes", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_list(
        &self,
        input: &oneiron::task_verb::sdk::EmptyRequest,
    ) -> Result<Vec<oneiron::task_verb::sdk::RoomEntry>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.list", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_messages(
        &self,
        input: &oneiron::task_verb::sdk::RoomRequest,
    ) -> Result<oneiron::workspace_roster::RoomPage, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.messages", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_claim(
        &self,
        input: &oneiron::task_verb::sdk::RoomClaimRequest,
    ) -> Result<oneiron::workspace_roster::RoomClaimOutcome, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.claim", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_speak(
        &self,
        input: &oneiron::memory::WitnessTurn,
    ) -> Result<oneiron::memory::WitnessReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.speak", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
}
