// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
use super::*;
pub const FACADE_VERB_CATALOG: [&str; 12] = [
    "witness",
    "claim_upsert",
    "recall",
    "receipts",
    "tasks.ask",
    "tasks.wait",
    "tasks.answer",
    "tasks.outcomes",
    "rooms.list",
    "rooms.messages",
    "rooms.claim",
    "rooms.speak",
];
impl OneironClient {
    pub fn agent_verb(
        &self,
        verb: &str,
        input: serde_json::Value,
    ) -> Result<serde_json::Value, MemoryError> {
        self.ensure_dispatch_pid()?;
        if !oneiron::task_verb::sdk::AGENT_VERBS.contains(&verb) {
            return Err(crate::error::bad_request(
                "unknown SDK agent verb",
                &["Use a tasks.* or rooms.* SDK agent verb."],
            ));
        }
        match &self.backend {
            Backend::Embedded(client) => {
                oneiron::task_verb::sdk::invoke(&client.memory(), verb, input)
            }
            Backend::Remote(client) => client.call(verb, &input),
        }
    }
    pub fn tasks_ask(
        &self,
        input: &oneiron::task_verb::TaskAskSpec,
    ) -> Result<oneiron::task_verb::TaskAskReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.ask", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_wait(
        &self,
        input: &oneiron::task_verb::sdk::TaskWaitRequest,
    ) -> Result<oneiron::task_verb::TaskWaitOutcome, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.wait", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_answer(
        &self,
        input: &oneiron::task_verb::sdk::TaskAnswerRequest,
    ) -> Result<oneiron::task_verb::TaskAskAnswer, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.answer", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn tasks_outcomes(
        &self,
        input: &oneiron::task_verb::TaskAskHandle,
    ) -> Result<Vec<oneiron::llm::decision::questions::CalibrationPair>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("tasks.outcomes", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_list(
        &self,
        input: &oneiron::task_verb::sdk::EmptyRequest,
    ) -> Result<Vec<oneiron::task_verb::sdk::RoomEntry>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.list", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_messages(
        &self,
        input: &oneiron::task_verb::sdk::RoomRequest,
    ) -> Result<Vec<oneiron::workspace_roster::RoomTurn>, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.messages", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_claim(
        &self,
        input: &oneiron::task_verb::sdk::RoomClaimRequest,
    ) -> Result<oneiron::workspace_roster::RoomClaimOutcome, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.claim", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
    pub fn rooms_speak(
        &self,
        input: &oneiron::memory::WitnessTurn,
    ) -> Result<oneiron::memory::WitnessReceipt, MemoryError> {
        let value = serde_json::to_value(input).map_err(|_| {
            crate::error::bad_request(
                "SDK input encoding failed",
                &["Send the documented typed SDK input."],
            )
        })?;
        let result = self.agent_verb("rooms.speak", value)?;
        serde_json::from_value(result).map_err(|_| {
            crate::error::bad_request(
                "SDK output decoding failed",
                &["Report this SDK response mismatch."],
            )
        })
    }
}
