[package]
name = "oneiron-napi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
oneiron = { path = "../oneiron" }
napi = { version = "3", default-features = false, features = ["napi8", "serde-json"] }
napi-derive = "3"
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
napi-build = "2"

[lints]
workspace = true
