/**
 * Three consumers share one wire contract; two of them share this artifact.
 *
 * 1. code mode — the sandbox host dispatcher. It speaks the same wire and does
 *    NOT import this package, so it appears here only as a non-import pin.
 * 2. `native-worker` — a native TypeScript worker importing the package.
 * 3. `byoa` — an npm-capable external agent installing the published package.
 *
 * Consumers 2 and 3 are proved on a real resolution, not on a comment: the
 * package is packed the way npm/Bun would pack it (its `files` list plus the
 * manifest), installed once into a temporary workspace's `node_modules`, and
 * imported by name from two different consumer directories. Both must land on
 * the same package root and the same `HttpBaseClient` object — one artifact,
 * never a fork per consumer.
 */
import { afterAll, describe, expect, test } from "bun:test";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { HttpBaseClient } from "../src/index";

interface PackageManifest {
  readonly name: string;
  readonly main?: string;
  readonly types?: string;
  readonly exports?: Record<string, string>;
  readonly files?: readonly string[];
  readonly scripts?: Record<string, string>;
  readonly dependencies?: Record<string, string>;
  readonly devDependencies?: Record<string, string>;
}

interface ClientModule {
  readonly HttpBaseClient: typeof HttpBaseClient;
}

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packagesDir = resolve(packageRoot, "..");
const manifestText = readFileSync(join(packageRoot, "package.json"), "utf8");
const manifest = JSON.parse(manifestText) as PackageManifest;
const workspaces: string[] = [];

/** Pack the package the way a registry would, then install it once. */
function installPackedArtifact(): { workspace: string; installed: string } {
  const workspace = mkdtempSync(join(tmpdir(), "oneiron-client-consumers-"));
  workspaces.push(workspace);

  const installed = join(workspace, "node_modules", "@oneiron", "client");
  mkdirSync(installed, { recursive: true });
  cpSync(join(packageRoot, "package.json"), join(installed, "package.json"));
  for (const entry of manifest.files ?? []) {
    cpSync(join(packageRoot, entry), join(installed, entry), { recursive: true });
  }

  return { workspace, installed };
}

function writeConsumer(workspace: string, relativeDir: string, name: string): string {
  const dir = join(workspace, relativeDir);
  mkdirSync(dir, { recursive: true });
  const entry = join(dir, "consumer.ts");
  writeFileSync(
    entry,
    `import { HttpBaseClient } from "@oneiron/client";\n` +
      `export const consumer = ${JSON.stringify(name)};\n` +
      `export { HttpBaseClient };\n`,
    "utf8",
  );
  return entry;
}

afterAll(() => {
  for (const workspace of workspaces) {
    rmSync(workspace, { recursive: true, force: true });
  }
});

describe("one artifact, one public entry point", () => {
  test("the manifest publishes exactly one source-direct export", () => {
    expect(manifest.name).toBe("@oneiron/client");
    expect(manifest.main).toBe("./src/index.ts");
    expect(manifest.types).toBe("./src/index.ts");
    expect(manifest.exports).toEqual({ ".": "./src/index.ts" });
    expect(Object.keys(manifest.dependencies ?? {})).toHaveLength(0);
    expect(existsSync(join(packageRoot, "src", "index.ts"))).toBe(true);
  });

  test("nothing here is generated and no build step produces an SDK", () => {
    const generatorMarkers = [
      "openapi-generator",
      "swagger-codegen",
      "openapi-typescript-codegen",
      "@hey-api/openapi-ts",
      "orval",
      "autorest",
    ];
    for (const marker of generatorMarkers) {
      expect(manifestText).not.toContain(marker);
    }
    for (const script of Object.keys(manifest.scripts ?? {})) {
      expect(["typecheck", "test", "check"]).toContain(script);
    }
    for (const generated of ["generated", "dist", join("src", "generated")]) {
      expect(existsSync(join(packageRoot, generated))).toBe(false);
    }

    const source = readFileSync(join(packageRoot, "src", "index.ts"), "utf8");
    for (const marker of ["@generated", "AUTOGENERATED", "DO NOT EDIT"]) {
      expect(source).not.toContain(marker);
    }
  });

  test("this repository ships no second client package", () => {
    const clientPackages = readdirSync(packagesDir)
      .filter((entry) => existsSync(join(packagesDir, entry, "package.json")))
      .map(
        (entry) =>
          (JSON.parse(
            readFileSync(join(packagesDir, entry, "package.json"), "utf8"),
          ) as PackageManifest).name,
      )
      .filter((name) => name.includes("client"));

    expect(clientPackages).toEqual(["@oneiron/client"]);
  });
});

describe("two importers resolve the same artifact", () => {
  test("the native worker and the packed BYOA consumer share one implementation", async () => {
    const { workspace, installed } = installPackedArtifact();

    // Different depths on purpose: each consumer resolves `@oneiron/client`
    // through ordinary node_modules lookup from where it happens to live.
    const workerEntry = writeConsumer(workspace, "native-worker", "native-worker");
    const byoaEntry = writeConsumer(workspace, join("byoa", "src", "agents"), "byoa");

    const worker = (await import(pathToFileURL(workerEntry).href)) as ClientModule & {
      consumer: string;
    };
    const byoa = (await import(pathToFileURL(byoaEntry).href)) as ClientModule & {
      consumer: string;
    };

    expect(worker.consumer).toBe("native-worker");
    expect(byoa.consumer).toBe("byoa");
    expect(worker.HttpBaseClient).toBe(byoa.HttpBaseClient);

    // The installed artifact is this package's source, not a copy that drifted.
    expect(readFileSync(join(installed, "src", "index.ts"), "utf8")).toBe(
      readFileSync(join(packageRoot, "src", "index.ts"), "utf8"),
    );
    expect(Object.getOwnPropertyNames(worker.HttpBaseClient.prototype)).toEqual(
      Object.getOwnPropertyNames(HttpBaseClient.prototype),
    );

    // And it is a working client, not just a resolvable file.
    const calls: string[] = [];
    const instance = new worker.HttpBaseClient({
      baseUrl: "http://127.0.0.1:3000",
      secret: "placeholder-secret-not-a-credential",
      fetch: ((input: URL | RequestInfo) => {
        calls.push(String(input));
        return Promise.resolve(new Response("{}"));
      }) as typeof globalThis.fetch,
    });
    const response = await instance.discover();
    expect(response.status).toBe(200);
    expect(calls).toEqual(["http://127.0.0.1:3000/api/core/discover"]);
  });

  test("code mode consumes the wire, never this artifact", () => {
    const source = readFileSync(join(packageRoot, "src", "index.ts"), "utf8");

    // No injector, and nothing that binds this client into a sandbox as the
    // code-mode dispatcher: that surface stays the host's.
    for (const marker of ["injectOneironClient", "self.oneiron", "globalThis.self"]) {
      expect(source).not.toContain(marker);
    }
  });
});
