// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
use super::*;
pub(super) fn routes() -> Router<Arc<SyncServer>> {
    Router::new()
        .route("/tasks.ask", post(tasks_ask))
        .route("/tasks.wait", post(tasks_wait))
        .route("/tasks.answer", post(tasks_answer))
        .route("/tasks.outcomes", post(tasks_outcomes))
        .route("/rooms.list", post(rooms_list))
        .route("/rooms.messages", post(rooms_messages))
        .route("/rooms.claim", post(rooms_claim))
        .route("/rooms.speak", post(rooms_speak))
}
async fn tasks_ask(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.ask",
        value,
    )?))
}
async fn tasks_wait(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.wait",
        value,
    )?))
}
async fn tasks_answer(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.answer",
        value,
    )?))
}
async fn tasks_outcomes(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.outcomes",
        value,
    )?))
}
async fn rooms_list(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.list",
        value,
    )?))
}
async fn rooms_messages(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.messages",
        value,
    )?))
}
async fn rooms_claim(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.claim",
        value,
    )?))
}
async fn rooms_speak(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;
    let value = facade_json(payload)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.speak",
        value,
    )?))
}
