// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
use super::*;
pub(super) fn routes() -> Router<Arc<SyncServer>> {
    Router::new()
        .route("/witness", post(witness))
        .route("/claim_upsert", post(claim_upsert))
        .route("/recall", post(recall))
        .route("/receipts", post(receipts))
        .route("/key_value_get", post(key_value_get))
        .route("/key_value_put", post(key_value_put))
        .route("/key_value_delete", post(key_value_delete))
        .route("/key_value_search", post(key_value_search))
        .route("/key_value_namespaces", post(key_value_namespaces))
        .route("/tasks.ask", post(tasks_ask))
        .route("/tasks.wait", post(tasks_wait))
        .route("/tasks.answer", post(tasks_answer))
        .route("/tasks.outcomes", post(tasks_outcomes))
        .route("/rooms.list", post(rooms_list))
        .route("/rooms.messages", post(rooms_messages))
        .route("/rooms.claim", post(rooms_claim))
        .route("/rooms.speak", post(rooms_speak))
}
async fn witness(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("witness", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "witness",
        value,
    )?))
}
async fn claim_upsert(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("claim_upsert", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "claim_upsert",
        value,
    )?))
}
/// `POST /v1/core/facade/recall` → `Memory::recall`.
///
/// The lease argument is `None` and is not a client input: no lease-issuer
/// exists, and a bearer slip is not one. `Effort::High` therefore returns the
/// engine's own `LEASE_REQUIRED`, which this projection forwards as that exact
/// code — the bindings neither mint nor simulate a lease.
async fn recall(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;
    auth.require_unrestricted_record_scope()?;
    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("recall", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "recall",
        value,
    )?))
}
async fn receipts(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;
    auth.require_unrestricted_record_scope()?;
    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("receipts", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "receipts",
        value,
    )?))
}
async fn key_value_get(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("key_value_get", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "key_value_get",
        value,
    )?))
}
async fn key_value_put(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("key_value_put", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "key_value_put",
        value,
    )?))
}
async fn key_value_delete(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("key_value_delete", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "key_value_delete",
        value,
    )?))
}
async fn key_value_search(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("key_value_search", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "key_value_search",
        value,
    )?))
}
async fn key_value_namespaces(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;

    let value = facade_json(payload)?;
    oneiron::task_verb::sdk::validate_input("key_value_namespaces", &value)?;
    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "key_value_namespaces",
        value,
    )?))
}
async fn tasks_ask(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.ask",
        value,
    )?))
}
async fn tasks_wait(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.wait",
        value,
    )?))
}
async fn tasks_answer(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.answer",
        value,
    )?))
}
async fn tasks_outcomes(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "tasks.outcomes",
        value,
    )?))
}
async fn rooms_list(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.list",
        value,
    )?))
}
async fn rooms_messages(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Read)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.messages",
        value,
    )?))
}
async fn rooms_claim(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.claim",
        value,
    )?))
}
async fn rooms_speak(
    auth: CoreAuth,
    State(server): State<Arc<SyncServer>>,
    payload: Result<Json<serde_json::Value>, JsonRejection>,
) -> Result<Json<serde_json::Value>, FacadeApiError> {
    auth.require(CoreScope::Write)?;

    let value = facade_json(payload)?;

    let (actor, class) = facade_actor(&auth)?;
    Ok(Json(oneiron::task_verb::sdk::invoke(
        &server.vault.memory(actor, class),
        "rooms.speak",
        value,
    )?))
}
