// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
export_facade! {
"witness" => fn witness(&self, turn: WitnessTurn) -> WitnessReceipt;
"claimUpsert" => fn claim_upsert(&self, claim: ClaimInput) -> CommitReceipt;
"recall" => fn recall(&self, query: String, effort: Effort, scope: Option<RecallScope>, limit: u32, format: Option<String>) -> MemoryPack;
"receipts" => fn receipts(&self, limit: u32) -> Vec<FacadeReceipt>;
"commit" => fn commit(&self, claims: Vec<ClaimInput>) -> Vec<CommitReceipt>;
"remember" => fn remember(&self, claim: ClaimInput) -> CommitReceipt;
"claimRetract" => fn claim_retract(&self, claim_ref: String) -> CommitReceipt;
"forget" => fn forget(&self, selector: ForgetSelector) -> Vec<CommitReceipt>;
"claimList" => fn claim_list(&self, filter: ClaimListFilter) -> ClaimViews;
"claimHistory" => fn claim_history(&self, claim_ref: String) -> ClaimViews;
"safeDelete" => fn safe_delete(&self, entity_ref: String, reason: SafeDeleteReason) -> DeleteReceipt;
"pendingWrites" => fn pending_writes(&self, limit: u32) -> Vec<PendingWrite>;
"hydrate" => fn hydrate(&self, refs: Vec<String>) -> EntityViews;
"getEntity" => fn get_entity(&self, entity_ref: String) -> EntityRead;
"queryBm25" => fn query_bm25(&self, query: String, limit: u32) -> LexicalHits;
"neighbors" => fn neighbors(&self, entity_ref: String, opts: NeighborOpts) -> NeighborHits;
"putStructural" => fn put_structural(&self, input: StructuralPutInput) -> EntityRefReceipt;
"putHabitCheckin" => fn put_habit_checkin(&self, input: HabitCheckinInput) -> EntityRefReceipt;
"putCompanionRecord" => fn put_companion_record(&self, input: CompanionRecordInput) -> EntityRefReceipt;
"admitImportedClaim" => fn admit_imported_claim(&self, input: AdmitImportedClaimInput) -> CommitReceipt;
"putBlobArtifact" => fn put_blob_artifact(&self, input: BlobArtifactInput) -> EntityRefReceipt;
"appendBlobVersion" => fn append_blob_version(&self, artifact_ref: String, content: Vec<u8>, run_ref: Option<String>, occurred_at: Option<i64>, learned_at: Option<i64>) -> BlobVersionView;
"readBlobVersion" => fn read_blob_version(&self, artifact_ref: String, version: u64) -> Option<Vec<u8>>;
"enqueueConsolidation" => fn enqueue_consolidation(&self, input: ConsolidationJobInput) -> DreamerJobRef;
"dreamerJobStatus" => fn dreamer_job_status(&self, job_ref: String) -> Option<DreamerJobView>;
"seedClaims" => fn seed_claims(&self, claims: Vec<ClaimInput>) -> Vec<CommitReceipt>;
"scheduleOutbound" => fn schedule_outbound(&self, draft: OutboundDraftInput) -> OutboundIntentReceipt;
}
