//! Companion control-plane surface: access grants, psych-mirror profiles, and the
//! companion register record lifecycle. Reads are gated by AccessGrant scopes; the
//! child modules own one domain each and this module only re-exports the seam.

mod access_grants;
mod auth;
mod errors;
mod profiles;
mod register;
mod register_wire;

pub(crate) use self::access_grants::{
    CompanionAccessGrantResponse, CompanionAccessGrantScopePayload,
    CompanionCreateAccessGrantRequest, CompanionRevokeAccessGrantRequest,
    create_companion_access_grant, revoke_companion_access_grant,
};
// Utoipa path-registration structs generated by `#[utoipa::path]` on the handlers;
// the `OpenApi` derive in `super` resolves them through this seam.
pub(crate) use self::access_grants::{
    __path_create_companion_access_grant, __path_revoke_companion_access_grant,
};
pub(crate) use self::auth::auth_bound_principal_ref;
pub(crate) use self::profiles::{__path_get_companion_profile, __path_refresh_companion_profile};
pub(crate) use self::profiles::{
    CompanionProfileAccess, CompanionProfileConfidencePayload, CompanionProfileDriftAnchor,
    CompanionProfileNextAction, CompanionProfilePayload, CompanionProfileRefreshRequest,
    CompanionProfileResponse, CompanionProfileStaleReasonPayload, get_companion_profile,
    refresh_companion_profile,
};
pub(crate) use self::register::{
    __path_create_companion_register_record, __path_end_companion_register_relationship,
    __path_get_companion_register_record, __path_retire_companion_register_record,
    __path_update_companion_register_record,
};
pub(crate) use self::register::{
    CompanionEndRelationshipRequest, CompanionRegisterCreateRecordRequest,
    CompanionRegisterProvenancePayload, CompanionRegisterRecordPayload,
    CompanionRegisterRelationshipRefPayload, CompanionRegisterRetireRecordRequest,
    CompanionRegisterScopePayload, CompanionRegisterSubjectPayload,
    CompanionRegisterUpdateRecordRequest, create_companion_register_record,
    end_companion_register_relationship, get_companion_register_record,
    retire_companion_register_record, update_companion_register_record,
};
pub(crate) use self::register_wire::{
    CompanionEndRelationshipResponse, CompanionGoodbyeArtifactHookPayload,
    CompanionRegisterRecordResponse,
};
