//! Companion control-plane surface: access grants and psych-mirror profiles.
//! Reads are gated by AccessGrant scopes; child modules own one domain each and
//! this module only re-exports the seam.

mod access_grants;
mod auth;
mod errors;
mod lists;
mod profiles;

pub(crate) use self::access_grants::{
    CompanionAccessGrantResponse, CompanionAccessGrantScopePayload,
    CompanionCreateAccessGrantRequest, CompanionRevokeAccessGrantRequest,
    create_companion_access_grant, revoke_companion_access_grant,
};
// Utoipa path-registration structs generated by `#[utoipa::path]` on the handlers;
// the `OpenApi` derive in `super` resolves them through this seam.
pub(crate) use self::access_grants::{
    __path_create_companion_access_grant, __path_revoke_companion_access_grant,
};
pub(crate) use self::auth::auth_bound_principal_ref;
pub(crate) use self::profiles::{__path_get_companion_profile, __path_refresh_companion_profile};
pub(crate) use self::profiles::{
    CompanionProfileAccess, CompanionProfileConfidencePayload, CompanionProfileDriftAnchor,
    CompanionProfileNextAction, CompanionProfilePayload, CompanionProfileRefreshRequest,
    CompanionProfileResponse, CompanionProfileStaleReasonPayload, get_companion_profile,
    refresh_companion_profile,
};

pub(crate) use self::lists::{
    __path_list_access_requests, __path_list_personas, AccessRequestListRow,
    AccessRequestsListResponse, PersonaListQuery, PersonaListRow, PersonasListResponse,
    list_access_requests, list_personas,
};
