// Generated by scripts/sdk/generate.py; edit agent-verbs.json instead.
export type AgentInvoke = (method: string, input: unknown) => unknown;
export interface OutcomeBinding { source: {kind: "claim" | "event"; predicate: string} | {kind: "edge"; relation: string} | {kind: "stage"; campaign: string}; horizon: number; mapping: Record<string, boolean>; noise_weight: number; linked_by?: string | null }
export interface CalibrationPair { prediction: unknown; probability: number; outcome: {answer: string; fact: string; fact_value_hash: number[]; label: boolean; noise_weight: number; occurred_at: number} }
export interface TaskAskSpec { question: Record<string, unknown>; holders: string[]; idempotency_key: string; outcome_binding?: OutcomeBinding | null }
export interface TaskAskHandle { task_ref: string }
export interface TaskAskReceipt { handle: TaskAskHandle; count: number; replayed: boolean }
export interface TaskAskAnswer { task_ref: string; actor_ref: string; result_ref: string; at: number; answer_ref: string | null; question_version: number | null }
export type TaskWaitOutcome = { Pending: {trap_ref: string} } | { Ready: TaskAskAnswer } | { AlreadyResumed: TaskAskAnswer };
export function agentVerbs(invoke: AgentInvoke) {
  return {
tasks: {
ask(spec: TaskAskSpec): TaskAskReceipt { return invoke("tasksAsk", spec) as TaskAskReceipt },
wait(handle: TaskAskHandle, stepKey = "sdk.wait"): TaskWaitOutcome { return invoke("tasksWait", {handle, step_key: stepKey}) as TaskWaitOutcome },
answer(handle: TaskAskHandle, resultRef: string): TaskAskAnswer { return invoke("tasksAnswer", {handle, result_ref: resultRef}) as TaskAskAnswer },
outcomes(handle: TaskAskHandle): CalibrationPair[] { return invoke("tasksOutcomes", handle) as CalibrationPair[] },
},
rooms: {
list(): unknown[] { return invoke("roomsList", {}) as unknown[] },
messages(roomRef: string, after?: string, limit?: number): unknown[] { return invoke("roomsMessages", {room_ref: roomRef, after, limit}) as unknown[] },
claim(roomRef: string, turnRef: string): unknown { return invoke("roomsClaim", {room_ref: roomRef, turn_ref: turnRef}) as unknown },
speak(turn: Record<string, unknown>): unknown { return invoke("roomsSpeak", turn) as unknown },
},
}
}
