/**
 * The private native binding seam.
 *
 * This module is NOT part of the package's public surface: `src/index.ts` is
 * the only export entry, and it re-exports `Oneiron` and `OneironError` only.
 * `NativeClient` is held by the wrapper and never handed out, which is what
 * keeps `VaultBridge`, `ActorScopedVault`, and every other raw native class
 * out of the flagship package.
 *
 * There is deliberately no HTTP client here or anywhere else in this package.
 * `connect()` reaches `oneiron-server` through the one Rust stack owned by
 * `oneiron-remote`, so JavaScript never holds a URL, a timeout, or a route.
 */

import { createRequire } from "node:module"

import type {
  ClaimInput,
  CommitReceipt,
  FacadeReceipt,
  MemoryPack,
  RecallScope,
  WitnessReceipt,
  WitnessTurn,
} from "./types.js"

/** The native class's shape, as generated by napi-rs. */
export interface NativeClient {
  asActor(actorKey: string): NativeClient
  witness(turn: WitnessTurn): WitnessReceipt
  claimUpsert(claim: ClaimInput): CommitReceipt
  recall(
    query: string,
    effort: string | undefined,
    scope: RecallScope | undefined,
    limit: number | undefined,
    format: string | undefined,
  ): MemoryPack
  receipts(limit: number | undefined): FacadeReceipt[]
}

/** The static half napi-rs generates for a `#[napi(factory)]` constructor. */
interface NativeClientConstructor {
  open(path: string | undefined, dimensions: number | undefined): NativeClient
  connect(url: string, key: string): NativeClient
}

interface NativeBinding {
  NativeClient: NativeClientConstructor
}

// napi-rs emits a CommonJS loader that picks the right prebuilt `.node`
// artifact for the running platform, so it is `require`d rather than imported:
// the selection is a runtime decision this package must not try to make in a
// static import specifier.
const require = createRequire(import.meta.url)
const binding = require("../native/index.js") as NativeBinding

export const NativeClient: NativeClientConstructor = binding.NativeClient
